# Generated by Django 6.1.1 on 2026-10-08 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptikForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120, unique=True, verbose_name='Form adı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('satir_uzunluk', models.PositiveIntegerField(verbose_name='Satır uzunluğu')),
                ('kodlama', models.CharField(default='cp1254', help_text='cp1254 Türkçe Windows, utf-8 düz metin.', max_length=20, verbose_name='Harf düzeni')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Optik form',
                'verbose_name_plural': 'Optik formlar',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='OptikFormAlani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('tc', 'TC'), ('numara', 'Öğrenci no'), ('numara_kontrol', 'Numara taşma kontrolü'), ('kitapcik', 'Kitapçık'), ('sinif', 'Sınıf'), ('sube', 'Şube'), ('ad', 'Ad soyad'), ('sik', 'Şık bölgesi')], max_length=20, verbose_name='Tür')),
                ('baslangic', models.PositiveIntegerField(verbose_name='Başlangıç kolonu')),
                ('bitis', models.PositiveIntegerField(verbose_name='Bitiş kolonu')),
                ('sira', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alanlar', to='sinav_okuma.optikform', verbose_name='Form')),
            ],
            options={
                'verbose_name': 'Optik form alanı',
                'verbose_name_plural': 'Optik form alanları',
                'ordering': ['sira', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Sinav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Sınav adı')),
                ('tarih', models.DateField(verbose_name='Sınav tarihi')),
                ('anahtar_a', models.TextField(blank=True, verbose_name='A kitapçık anahtarı')),
                ('anahtar_b', models.TextField(blank=True, verbose_name='B kitapçık anahtarı')),
                ('dagilim', models.TextField(blank=True, help_text='Şeritteki sıra. Her satır: turkce 15', verbose_name='Ders sırası')),
                ('kazanimlar', models.TextField(blank=True, help_text='İsteğe bağlı. Her satır bir soru, şeritteki sırayla.', verbose_name='Soru kazanımları')),
                ('okuma_notu', models.TextField(blank=True, verbose_name='Son okuma notu')),
                ('son_dosya', models.CharField(blank=True, max_length=255, verbose_name='Son dosya')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sinavlar', to='sinav_okuma.optikform', verbose_name='Optik form')),
            ],
            options={
                'verbose_name': 'Sınav',
                'verbose_name_plural': 'Sınavlar',
                'ordering': ['-tarih', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SinavSatiri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satir_no', models.PositiveIntegerField(verbose_name='Dosya satırı')),
                ('ogrenci_no', models.CharField(blank=True, max_length=32, verbose_name='Öğrenci no')),
                ('ad', models.CharField(max_length=200, verbose_name='Ad soyad')),
                ('kitapcik', models.CharField(blank=True, max_length=4, verbose_name='Kitapçık')),
                ('sinif_metni', models.CharField(blank=True, max_length=120, verbose_name='Sınıf')),
                ('uyarilar', models.TextField(blank=True, verbose_name='Notlar')),
                ('cevaplar', models.TextField(blank=True, verbose_name='Şık şeridi')),
                ('puanlandi', models.BooleanField(default=False, verbose_name='Puanlandı')),
                ('dogru', models.PositiveIntegerField(default=0)),
                ('yanlis', models.PositiveIntegerField(default=0)),
                ('bos', models.PositiveIntegerField(default=0)),
                ('net', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('puan', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sinav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satirlar', to='sinav_okuma.sinav', verbose_name='Sınav')),
            ],
            options={
                'verbose_name': 'Sınav satırı',
                'verbose_name_plural': 'Sınav satırları',
                'ordering': ['satir_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SinavSoru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders_key', models.CharField(max_length=40)),
                ('soru_no', models.PositiveIntegerField()),
                ('sonuc', models.CharField(max_length=10)),
                ('konu_ad', models.CharField(blank=True, max_length=300)),
                ('sira', models.PositiveIntegerField(default=0)),
                ('satir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorular', to='sinav_okuma.sinavsatiri', verbose_name='Satır')),
            ],
            options={
                'verbose_name': 'Sınav sorusu',
                'verbose_name_plural': 'Sınav soruları',
                'ordering': ['sira', 'id'],
            },
        ),
    ]
