# Generated by Django 6.1.1 on 2026-10-08 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinav_okuma', '0002_ornek_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinav',
            name='anahtar_ad',
            field=models.CharField(blank=True, max_length=200, verbose_name='Anahtar dosyasındaki sınav'),
        ),
        migrations.AddField(
            model_name='sinav',
            name='anahtar_dosya',
            field=models.CharField(blank=True, max_length=255, verbose_name='Anahtar dosyası'),
        ),
        migrations.AddField(
            model_name='sinav',
            name='sinif_etiket',
            field=models.CharField(blank=True, max_length=80, verbose_name='Sınıf'),
        ),
        migrations.CreateModel(
            name='SinavAnahtarSoru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira', models.PositiveIntegerField(verbose_name='A kitapçık sırası')),
                ('ders_key', models.CharField(max_length=40)),
                ('ders_ad', models.CharField(max_length=120)),
                ('test_ad', models.CharField(blank=True, max_length=120)),
                ('a_no', models.PositiveIntegerField()),
                ('b_no', models.PositiveIntegerField(blank=True, null=True)),
                ('cevap', models.CharField(max_length=1)),
                ('kazanim_kodu', models.CharField(blank=True, max_length=40)),
                ('kazanim', models.TextField(blank=True)),
                ('sinav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anahtar_sorulari', to='sinav_okuma.sinav', verbose_name='Sınav')),
            ],
            options={
                'verbose_name': 'Cevap anahtarı sorusu',
                'verbose_name_plural': 'Cevap anahtarı soruları',
                'ordering': ['sira', 'id'],
                'constraints': [models.UniqueConstraint(fields=('sinav', 'sira'), name='sinav_anahtar_sira'), models.UniqueConstraint(fields=('sinav', 'ders_key', 'a_no'), name='sinav_anahtar_a_no')],
            },
        ),
    ]
