# Generated by Django 6.0.7 on 2026-08-04 14:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtutHocasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=120)),
                ('aktif', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etut_profili', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etüt hocası',
                'verbose_name_plural': 'Etüt hocaları',
                'ordering': ['ad_soyad'],
            },
        ),
        migrations.CreateModel(
            name='Kitap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('ad', models.CharField(max_length=220)),
                ('yazar', models.CharField(blank=True, max_length=160)),
                ('yayinevi', models.CharField(blank=True, max_length=160)),
                ('toplam_sayfa', models.PositiveIntegerField()),
                ('sinif_seviyesi', models.CharField(blank=True, max_length=40)),
                ('aciklama', models.TextField(blank=True)),
                ('aktif', models.BooleanField(default=True)),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_olusturdu', to=settings.AUTH_USER_MODEL)),
                ('son_duzenleyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_duzenledi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kitap',
                'verbose_name_plural': 'Kitaplar',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Talebe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=120)),
                ('sinif', models.CharField(max_length=20)),
                ('sube', models.CharField(blank=True, max_length=10)),
                ('aktif', models.BooleanField(default=True)),
                ('etut_hocasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talebeler', to='takip.etuthocasi')),
            ],
            options={
                'verbose_name': 'Talebe',
                'verbose_name_plural': 'Talebeler',
                'ordering': ['sinif', 'sube', 'ad_soyad'],
            },
        ),
        migrations.CreateModel(
            name='Zimmet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('zimmet_tarihi', models.DateField(default=django.utils.timezone.localdate)),
                ('hedef_bitis_tarihi', models.DateField(blank=True, null=True)),
                ('baslangic_sayfasi', models.PositiveIntegerField(default=0)),
                ('durum', models.CharField(choices=[('okunuyor', 'Okunuyor'), ('tamamlandi', 'Tamamlandı'), ('sinav_bekliyor', 'Sınav Bekliyor'), ('sinav_yapildi', 'Sınav Yapıldı'), ('yarim', 'Yarım Bırakıldı'), ('iade', 'İade Edildi')], default='okunuyor', max_length=30)),
                ('etut_hocasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zimmetler', to='takip.etuthocasi')),
                ('kitap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zimmetler', to='takip.kitap')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_olusturdu', to=settings.AUTH_USER_MODEL)),
                ('son_duzenleyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_duzenledi', to=settings.AUTH_USER_MODEL)),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zimmetler', to='takip.talebe')),
            ],
            options={
                'verbose_name': 'Kitap zimmeti',
                'verbose_name_plural': 'Kitap zimmetleri',
                'ordering': ['-zimmet_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='OkumaKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('tarih', models.DateField(default=django.utils.timezone.localdate)),
                ('son_sayfa', models.PositiveIntegerField()),
                ('not_metni', models.CharField(blank=True, max_length=300)),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_olusturdu', to=settings.AUTH_USER_MODEL)),
                ('son_duzenleyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_duzenledi', to=settings.AUTH_USER_MODEL)),
                ('zimmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='okuma_kayitlari', to='takip.zimmet')),
            ],
            options={
                'verbose_name': 'Günlük okuma kaydı',
                'verbose_name_plural': 'Günlük okuma kayıtları',
                'ordering': ['-tarih', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KitapSinavi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('tarih', models.DateField(default=django.utils.timezone.localdate)),
                ('toplam_soru', models.PositiveIntegerField(default=10)),
                ('dogru', models.PositiveIntegerField(default=0)),
                ('yanlis', models.PositiveIntegerField(default=0)),
                ('bos', models.PositiveIntegerField(default=0)),
                ('puan', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('degerlendirme', models.TextField(blank=True)),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_olusturdu', to=settings.AUTH_USER_MODEL)),
                ('son_duzenleyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_duzenledi', to=settings.AUTH_USER_MODEL)),
                ('zimmet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sinav', to='takip.zimmet')),
            ],
            options={
                'verbose_name': 'Kitap sınavı',
                'verbose_name_plural': 'Kitap sınavları',
                'ordering': ['-tarih'],
            },
        ),
        migrations.AddConstraint(
            model_name='kitap',
            constraint=models.UniqueConstraint(fields=('ad', 'yazar'), name='benzersiz_kitap_yazar'),
        ),
        migrations.AddConstraint(
            model_name='okumakaydi',
            constraint=models.UniqueConstraint(fields=('zimmet', 'tarih'), name='zimmet_gunluk_tek_kayit'),
        ),
    ]
