# Generated by Django 6.0.7 on 2026-08-04 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Sınav adı')),
                ('soru_sayisi', models.PositiveIntegerField(verbose_name='Soru sayısı')),
                ('sinav_tarihi', models.DateField(verbose_name='Sınav tarihi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('etut_hocasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sinavlar', to='takip.etuthocasi', verbose_name='Etüt hocası')),
                ('kitap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sinavlar', to='takip.kitap', verbose_name='Kitap')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_sinavlar', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan kullanıcı')),
            ],
            options={
                'verbose_name': 'Sınav',
                'verbose_name_plural': 'Sınavlar',
                'ordering': ['-sinav_tarihi', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SinavSonucu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogru', models.PositiveIntegerField(default=0, verbose_name='Doğru')),
                ('yanlis', models.PositiveIntegerField(default=0, verbose_name='Yanlış')),
                ('bos', models.PositiveIntegerField(default=0, verbose_name='Boş')),
                ('puan', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, verbose_name='Puan')),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt tarihi')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('kaydeden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaydettigi_sinav_sonuclari', to=settings.AUTH_USER_MODEL, verbose_name='Kaydeden kullanıcı')),
                ('sinav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sonuclar', to='takip.sinav', verbose_name='Sınav')),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinav_sonuclari', to='takip.talebe', verbose_name='Talebe')),
            ],
            options={
                'verbose_name': 'Sınav sonucu',
                'verbose_name_plural': 'Sınav sonuçları',
                'ordering': ['-puan', '-dogru', 'talebe__ad_soyad'],
                'constraints': [models.UniqueConstraint(fields=('sinav', 'talebe'), name='sinav_talebe_tek_sonuc')],
            },
        ),
    ]
