# Generated by Django 6.0.7 on 2026-08-05 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0002_sinav_sinavsonucu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='talebe',
            name='talebe_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Talebe numarası'),
        ),
        migrations.AlterField(
            model_name='etuthocasi',
            name='ad_soyad',
            field=models.CharField(max_length=120, verbose_name='Ad soyad'),
        ),
        migrations.AlterField(
            model_name='etuthocasi',
            name='aktif',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='etuthocasi',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etut_profili', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı hesabı'),
        ),
        migrations.AlterField(
            model_name='talebe',
            name='ad_soyad',
            field=models.CharField(max_length=120, verbose_name='Ad soyad'),
        ),
        migrations.AlterField(
            model_name='talebe',
            name='aktif',
            field=models.BooleanField(default=True, verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='talebe',
            name='etut_hocasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talebeler', to='takip.etuthocasi', verbose_name='Etüt hocası'),
        ),
        migrations.AlterField(
            model_name='talebe',
            name='sinif',
            field=models.CharField(blank=True, max_length=20, verbose_name='Sınıf'),
        ),
        migrations.AlterField(
            model_name='talebe',
            name='sube',
            field=models.CharField(blank=True, max_length=10, verbose_name='Şube'),
        ),
        migrations.CreateModel(
            name='SinifSube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinif', models.CharField(choices=[('5', '5. Sınıf'), ('6', '6. Sınıf'), ('7', '7. Sınıf'), ('8', '8. Sınıf')], max_length=1, verbose_name='Sınıf')),
                ('sube', models.CharField(choices=[('A', 'A Şubesi'), ('B', 'B Şubesi')], max_length=1, verbose_name='Şube')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Sınıf ve şube',
                'verbose_name_plural': 'Sınıf ve şubeler',
                'ordering': ['sinif', 'sube'],
                'constraints': [models.UniqueConstraint(fields=('sinif', 'sube'), name='benzersiz_sinif_sube')],
            },
        ),
        migrations.AddField(
            model_name='etuthocasi',
            name='sorumlu_sinif_subeler',
            field=models.ManyToManyField(blank=True, related_name='etut_hocalari', to='takip.sinifsube', verbose_name='Sorumlu olduğu sınıf ve şubeler'),
        ),
        migrations.AddField(
            model_name='talebe',
            name='sinif_sube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='talebeler', to='takip.sinifsube', verbose_name='Sınıf ve şube'),
        ),
    ]
