# Generated by Django 6.0.7 on 2026-08-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0003_talebe_talebe_no_alter_etuthocasi_ad_soyad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinifsube',
            name='sinif',
            field=models.CharField(help_text='Örn. 3, 4, 5, Hazırlık, Mezun', max_length=30, verbose_name='Sınıf'),
        ),
        migrations.AlterField(
            model_name='sinifsube',
            name='sube',
            field=models.CharField(help_text='Örn. A, B, C', max_length=20, verbose_name='Şube'),
        ),
    ]
