# Generated by Django 6.1 on 2026-08-06 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0009_imammuezzinlistesi_imammuezzinatama'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemizlikAlani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120, verbose_name='Alan adı')),
                ('aciklama', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Temizlik alanı',
                'verbose_name_plural': 'Temizlik alanları',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='guncellenme',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='olusturulma',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imammuezzinlistesi',
            name='guncellenme',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='imammuezzinlistesi',
            name='olusturulma',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='imammuezzinlistesi',
            name='talebe_havuzu',
            field=models.ManyToManyField(blank=True, help_text='Boş bırakılırsa tüm aktif talebeler kullanılır.', related_name='imam_muezzin_listeleri', to='takip.talebe', verbose_name='Talebe havuzu'),
        ),
        migrations.AlterField(
            model_name='personelprofili',
            name='guncellenme',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='personelprofili',
            name='olusturulma',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='programplan',
            name='guncellenme',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='programplan',
            name='olusturulma',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='TemizlikListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Liste adı')),
                ('baslangic_tarihi', models.DateField(verbose_name='Başlangıç tarihi')),
                ('bitis_tarihi', models.DateField(verbose_name='Bitiş tarihi')),
                ('cumartesi_dahil', models.BooleanField(default=True, verbose_name='Cumartesi dahil')),
                ('pazar_dahil', models.BooleanField(default=False, verbose_name='Pazar dahil')),
                ('haric_tarihler', models.JSONField(blank=True, default=list, help_text='ISO formatında tarih listesi (YYYY-MM-DD).', verbose_name='Hariç tutulan günler')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('alanlar', models.ManyToManyField(blank=True, help_text='Boş bırakılırsa tüm aktif alanlar kullanılır.', related_name='temizlik_listeleri', to='takip.temizlikalani', verbose_name='Temizlik alanları')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_temizlik_listeleri', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('talebe_havuzu', models.ManyToManyField(blank=True, help_text='Boş bırakılırsa tüm aktif talebeler kullanılır.', related_name='temizlik_listeleri', to='takip.talebe', verbose_name='Talebe havuzu')),
            ],
            options={
                'verbose_name': 'Temizlik listesi',
                'verbose_name_plural': 'Temizlik listeleri',
                'ordering': ['-baslangic_tarihi', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='TemizlikAtama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('manuel_duzenlendi', models.BooleanField(default=False, verbose_name='Manuel düzenlendi')),
                ('alan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atamalar', to='takip.temizlikalani', verbose_name='Alan')),
                ('talebe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='temizlik_gorevleri', to='takip.talebe', verbose_name='Sorumlu talebe')),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atamalar', to='takip.temizliklistesi', verbose_name='Liste')),
            ],
            options={
                'verbose_name': 'Temizlik ataması',
                'verbose_name_plural': 'Temizlik atamaları',
                'ordering': ['tarih', 'alan__sira', 'alan__ad'],
                'constraints': [models.UniqueConstraint(fields=('liste', 'tarih', 'alan'), name='benzersiz_temizlik_liste_gun_alan')],
            },
        ),
    ]
