# Generated by Django 6.1 on 2026-08-06 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0010_temizlik'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YemekOgun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120, verbose_name='Öğün adı')),
                ('aciklama', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Yemek öğünü',
                'verbose_name_plural': 'Yemek öğünleri',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='YemekciListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Liste adı')),
                ('baslangic_tarihi', models.DateField(verbose_name='Başlangıç tarihi')),
                ('bitis_tarihi', models.DateField(verbose_name='Bitiş tarihi')),
                ('cumartesi_dahil', models.BooleanField(default=True, verbose_name='Cumartesi dahil')),
                ('pazar_dahil', models.BooleanField(default=False, verbose_name='Pazar dahil')),
                ('haric_tarihler', models.JSONField(blank=True, default=list, help_text='ISO formatında tarih listesi (YYYY-MM-DD).', verbose_name='Hariç tutulan günler')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_yemekci_listeleri', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('talebe_havuzu', models.ManyToManyField(blank=True, help_text='Boş bırakılırsa tüm aktif talebeler kullanılır.', related_name='yemekci_listeleri', to='takip.talebe', verbose_name='Talebe havuzu')),
                ('ogunler', models.ManyToManyField(blank=True, help_text='Boş bırakılırsa tüm aktif öğünler kullanılır.', related_name='yemekci_listeleri', to='takip.yemekogun', verbose_name='Öğünler')),
            ],
            options={
                'verbose_name': 'Yemekçilik listesi',
                'verbose_name_plural': 'Yemekçilik listeleri',
                'ordering': ['-baslangic_tarihi', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='YemekciAtama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('manuel_duzenlendi', models.BooleanField(default=False, verbose_name='Manuel düzenlendi')),
                ('talebe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='yemekci_gorevleri', to='takip.talebe', verbose_name='Sorumlu talebe')),
                ('yardimci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='yemekci_yardimci_gorevleri', to='takip.talebe', verbose_name='Yardımcı talebe')),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atamalar', to='takip.yemekcilistesi', verbose_name='Liste')),
                ('ogun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atamalar', to='takip.yemekogun', verbose_name='Öğün')),
            ],
            options={
                'verbose_name': 'Yemekçilik ataması',
                'verbose_name_plural': 'Yemekçilik atamaları',
                'ordering': ['tarih', 'ogun__sira', 'ogun__ad'],
                'constraints': [models.UniqueConstraint(fields=('liste', 'tarih', 'ogun'), name='benzersiz_yemekci_liste_gun_ogun')],
            },
        ),
    ]
