# Generated by Django 6.1 on 2026-08-06 21:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0011_yemekcilik'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=80, unique=True, verbose_name='Branş')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Branş',
                'verbose_name_plural': 'Branşlar',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='DiniDersSeviyesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=80, unique=True, verbose_name='Seviye adı')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Dini ders seviyesi',
                'verbose_name_plural': 'Dini ders seviyeleri',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='EgitimYili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=40, verbose_name='Eğitim yılı')),
                ('baslangic', models.DateField(verbose_name='Başlangıç')),
                ('bitis', models.DateField(verbose_name='Bitiş')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Eğitim yılı',
                'verbose_name_plural': 'Eğitim yılları',
                'ordering': ['-baslangic'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True, verbose_name='Kod')),
                ('ad', models.CharField(max_length=120, verbose_name='Rol adı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sistem_rolu', models.BooleanField(default=False, help_text='Silinemez ve temel yapılandırma korunur.', verbose_name='Sistem rolü')),
                ('legacy_ana_rol', models.CharField(blank=True, help_text='PersonelProfili.ana_rol ile eşleştirme.', max_length=30, verbose_name='Eski ana rol kodu')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roller',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='YetkiModul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=50, unique=True, verbose_name='Modül kodu')),
                ('ad', models.CharField(max_length=120, verbose_name='Modül adı')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Yetki modülü',
                'verbose_name_plural': 'Yetki modülleri',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.AddField(
            model_name='talebe',
            name='dogum_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum tarihi'),
        ),
        migrations.AddField(
            model_name='talebe',
            name='durum',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('mezun', 'Mezun'), ('ayrildi', 'Ayrıldı')], default='aktif', max_length=10, verbose_name='Durum'),
        ),
        migrations.AddField(
            model_name='talebe',
            name='eposta',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-posta'),
        ),
        migrations.AddField(
            model_name='talebe',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem', models.CharField(max_length=80, verbose_name='İşlem')),
                ('modul', models.CharField(blank=True, max_length=50, verbose_name='Modül')),
                ('nesne_tipi', models.CharField(blank=True, max_length=80, verbose_name='Nesne tipi')),
                ('nesne_id', models.CharField(blank=True, max_length=40, verbose_name='Nesne ID')),
                ('detay', models.JSONField(blank=True, default=dict, verbose_name='Detay')),
                ('olusturulma', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarih')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_kayitlari', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Audit kaydı',
                'verbose_name_plural': 'Audit kayıtları',
                'ordering': ['-olusturulma'],
            },
        ),
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120, verbose_name='Ders adı')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('brans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dersler', to='takip.brans', verbose_name='Branş')),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.AddField(
            model_name='talebe',
            name='dini_ders_seviyesi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talebeler', to='takip.dinidersseviyesi', verbose_name='Dini ders seviyesi'),
        ),
        migrations.CreateModel(
            name='Donem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=80, verbose_name='Dönem adı')),
                ('baslangic', models.DateField(verbose_name='Başlangıç')),
                ('bitis', models.DateField(verbose_name='Bitiş')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('egitim_yili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donemler', to='takip.egitimyili', verbose_name='Eğitim yılı')),
            ],
            options={
                'verbose_name': 'Dönem',
                'verbose_name_plural': 'Dönemler',
                'ordering': ['-baslangic'],
            },
        ),
        migrations.AddField(
            model_name='personelprofili',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personel_profilleri', to='takip.rol', verbose_name='RBAC rolü'),
        ),
        migrations.CreateModel(
            name='RolKapsam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('tum', 'Tüm talebeler'), ('etut_grubu', 'Etüt grubu'), ('sinif_listesi', 'Sınıf listesi'), ('dini_seviye', 'Dini ders seviyesi')], default='etut_grubu', max_length=20, verbose_name='Kapsam tipi')),
                ('deger', models.JSONField(blank=True, default=dict, help_text='Örn. {"sinif_sube_ids": [1, 2]}', verbose_name='Kapsam değeri')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kapsamlar', to='takip.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Rol kapsamı',
                'verbose_name_plural': 'Rol kapsamları',
            },
        ),
        migrations.CreateModel(
            name='TalebeDosyasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='talebe_dosyalari/%Y/%m/', verbose_name='Dosya')),
                ('aciklama', models.CharField(blank=True, max_length=200, verbose_name='Açıklama')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosyalar', to='takip.talebe', verbose_name='Talebe')),
                ('yukleyen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yukledigi_talebe_dosyalari', to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen')),
            ],
            options={
                'verbose_name': 'Talebe dosyası',
                'verbose_name_plural': 'Talebe dosyaları',
                'ordering': ['-olusturulma'],
            },
        ),
        migrations.CreateModel(
            name='TalebeGenelDurum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ozet', models.TextField(blank=True, verbose_name='Genel durum özeti')),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('guncelleyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guncelledigi_genel_durumlar', to=settings.AUTH_USER_MODEL, verbose_name='Son güncelleyen')),
                ('talebe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='genel_durum', to='takip.talebe', verbose_name='Talebe')),
            ],
            options={
                'verbose_name': 'Talebe genel durum',
                'verbose_name_plural': 'Talebe genel durumlar',
            },
        ),
        migrations.CreateModel(
            name='TalebePersonelNotu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('icerik', models.TextField(verbose_name='İçerik')),
                ('staff_only', models.BooleanField(default=True, verbose_name='Yalnızca personel')),
                ('veliye_goster', models.BooleanField(default=False, verbose_name='Veli panelinde göster')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personel_notlari', to='takip.talebe', verbose_name='Talebe')),
                ('yazar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yazdigi_talebe_notlari', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'verbose_name': 'Talebe personel notu',
                'verbose_name_plural': 'Talebe personel notları',
                'ordering': ['-olusturulma'],
            },
        ),
        migrations.CreateModel(
            name='VeliHesap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=120, verbose_name='Ad soyad')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='veli_hesabi', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı hesabı')),
            ],
            options={
                'verbose_name': 'Veli hesabı',
                'verbose_name_plural': 'Veli hesapları',
            },
        ),
        migrations.CreateModel(
            name='VeliKisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yakinlik', models.CharField(choices=[('anne', 'Anne'), ('baba', 'Baba'), ('veli', 'Veli'), ('diger', 'Diğer')], default='veli', max_length=10, verbose_name='Yakınlık')),
                ('ad_soyad', models.CharField(max_length=120, verbose_name='Ad soyad')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('eposta', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('birincil', models.BooleanField(default=False, verbose_name='Birincil iletişim')),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veli_kisileri', to='takip.talebe', verbose_name='Talebe')),
            ],
            options={
                'verbose_name': 'Veli kişi',
                'verbose_name_plural': 'Veli kişiler',
                'ordering': ['-birincil', 'ad_soyad'],
            },
        ),
        migrations.CreateModel(
            name='YetkiIslem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=40, verbose_name='İşlem kodu')),
                ('ad', models.CharField(max_length=80, verbose_name='İşlem adı')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='islemler', to='takip.yetkimodul', verbose_name='Modül')),
            ],
            options={
                'verbose_name': 'Yetki işlemi',
                'verbose_name_plural': 'Yetki işlemleri',
                'ordering': ['modul__sira', 'sira', 'kod'],
            },
        ),
        migrations.CreateModel(
            name='RolModulErisim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erisim', models.BooleanField(default=False, verbose_name='Erişim')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modul_erisimleri', to='takip.rol', verbose_name='Rol')),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_erisimleri', to='takip.yetkimodul', verbose_name='Modül')),
            ],
            options={
                'verbose_name': 'Rol modül erişimi',
                'verbose_name_plural': 'Rol modül erişimleri',
            },
        ),
        migrations.CreateModel(
            name='KullaniciYetkiOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_kod', models.CharField(max_length=40, verbose_name='İşlem kodu')),
                ('etki', models.CharField(choices=[('grant', 'İzin ver'), ('deny', 'Engelle')], default='grant', max_length=10, verbose_name='Etki')),
                ('aciklama', models.CharField(blank=True, max_length=200, verbose_name='Açıklama')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yetki_overrides', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanici_overrides', to='takip.yetkimodul', verbose_name='Modül')),
            ],
            options={
                'verbose_name': 'Kullanıcı yetki override',
                'verbose_name_plural': "Kullanıcı yetki override'ları",
            },
        ),
        migrations.CreateModel(
            name='KullaniciRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birincil', models.BooleanField(default=True, verbose_name='Birincil rol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atanan_roller', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanicilar', to='takip.rol', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Kullanıcı rolü',
                'verbose_name_plural': 'Kullanıcı rolleri',
                'constraints': [models.UniqueConstraint(fields=('user', 'rol'), name='benzersiz_kullanici_rol')],
            },
        ),
        migrations.CreateModel(
            name='VeliTalebeBaglantisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yakinlik', models.CharField(choices=[('anne', 'Anne'), ('baba', 'Baba'), ('veli', 'Veli'), ('diger', 'Diğer')], default='veli', max_length=10, verbose_name='Yakınlık')),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veli_baglantilari', to='takip.talebe', verbose_name='Talebe')),
                ('veli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talebe_baglantilari', to='takip.velihesap', verbose_name='Veli')),
            ],
            options={
                'verbose_name': 'Veli–talebe bağlantısı',
                'verbose_name_plural': 'Veli–talebe bağlantıları',
                'constraints': [models.UniqueConstraint(fields=('veli', 'talebe'), name='benzersiz_veli_talebe')],
            },
        ),
        migrations.CreateModel(
            name='RolIslemYetki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izin', models.BooleanField(default=False, verbose_name='İzin')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='islem_yetkileri', to='takip.rol', verbose_name='Rol')),
                ('islem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_yetkileri', to='takip.yetkiislem', verbose_name='İşlem')),
            ],
            options={
                'verbose_name': 'Rol işlem yetkisi',
                'verbose_name_plural': 'Rol işlem yetkileri',
                'constraints': [models.UniqueConstraint(fields=('rol', 'islem'), name='benzersiz_rol_islem')],
            },
        ),
        migrations.AddConstraint(
            model_name='yetkiislem',
            constraint=models.UniqueConstraint(fields=('modul', 'kod'), name='benzersiz_modul_islem'),
        ),
        migrations.AddConstraint(
            model_name='rolmodulerisim',
            constraint=models.UniqueConstraint(fields=('rol', 'modul'), name='benzersiz_rol_modul'),
        ),
        migrations.AddConstraint(
            model_name='kullaniciyetkioverride',
            constraint=models.UniqueConstraint(fields=('user', 'modul', 'islem_kod'), name='benzersiz_kullanici_modul_islem'),
        ),
    ]
