# Generated by Django 6.1 on 2026-08-06 21:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0012_wave0_rbac_kernel_gelisim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KttSinav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='KTT adı')),
                ('sinif_seviyesi', models.CharField(help_text='Örn. 6, 7, 8', max_length=30, verbose_name='Sınıf seviyesi')),
                ('sinav_tarihi', models.DateField(verbose_name='Sınav tarihi')),
                ('soru_sayisi', models.PositiveIntegerField(verbose_name='Soru sayısı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('veliye_goster', models.BooleanField(default=True, verbose_name='Veli panelinde göster')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ktt_sinavlari', to='takip.ders', verbose_name='Ders')),
                ('etut_hocasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ktt_sinavlari', to='takip.etuthocasi', verbose_name='Etüt hocası')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_ktt_sinavlari', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'KTT',
                'verbose_name_plural': "KTT'ler",
                'ordering': ['-sinav_tarihi', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KttSonucu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogru', models.PositiveIntegerField(default=0, verbose_name='Doğru')),
                ('yanlis', models.PositiveIntegerField(default=0, verbose_name='Yanlış')),
                ('bos', models.PositiveIntegerField(default=0, verbose_name='Boş')),
                ('net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=6, verbose_name='Net')),
                ('puan', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5, verbose_name="100'lük puan")),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('kaydeden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaydettigi_ktt_sonuclari', to=settings.AUTH_USER_MODEL, verbose_name='Kaydeden')),
                ('ktt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sonuclar', to='takip.kttsinav', verbose_name='KTT')),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ktt_sonuclari', to='takip.talebe', verbose_name='Talebe')),
            ],
            options={
                'verbose_name': 'KTT sonucu',
                'verbose_name_plural': 'KTT sonuçları',
                'ordering': ['-puan', '-net', 'talebe__ad_soyad'],
                'constraints': [models.UniqueConstraint(fields=('ktt', 'talebe'), name='ktt_talebe_tek_sonuc')],
            },
        ),
    ]
