# Generated by Django 6.1 on 2026-08-06 21:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0013_ktt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GunlukSoruKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('kitap_okunan_sayfa', models.PositiveIntegerField(default=0, verbose_name='Kitap okunan sayfa')),
                ('gunluk_not', models.TextField(blank=True, verbose_name='Günlük not')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('kaydeden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaydettigi_soru_kayitlari', to=settings.AUTH_USER_MODEL, verbose_name='Kaydeden')),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gunluk_soru_kayitlari', to='takip.talebe', verbose_name='Talebe')),
            ],
            options={
                'verbose_name': 'Günlük soru kaydı',
                'verbose_name_plural': 'Günlük soru kayıtları',
                'ordering': ['-tarih', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GunlukSoruDersSatiri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toplam_soru', models.PositiveIntegerField(default=0, verbose_name='Toplam soru')),
                ('dogru', models.PositiveIntegerField(default=0, verbose_name='Doğru')),
                ('yanlis', models.PositiveIntegerField(default=0, verbose_name='Yanlış')),
                ('bos', models.PositiveIntegerField(default=0, verbose_name='Boş')),
                ('net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=8, verbose_name='Net')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gunluk_soru_satirlari', to='takip.ders', verbose_name='Ders')),
                ('kayit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ders_satirlari', to='takip.gunluksorukaydi', verbose_name='Kayıt')),
            ],
            options={
                'verbose_name': 'Günlük soru ders satırı',
                'verbose_name_plural': 'Günlük soru ders satırları',
            },
        ),
        migrations.AddConstraint(
            model_name='gunluksorukaydi',
            constraint=models.UniqueConstraint(fields=('talebe', 'tarih'), name='talebe_gunluk_soru_tek_kayit'),
        ),
        migrations.AddConstraint(
            model_name='gunluksoruderssatiri',
            constraint=models.UniqueConstraint(fields=('kayit', 'ders'), name='gunluk_soru_kayit_ders_benzersiz'),
        ),
    ]
