# Generated by Django 6.1 on 2026-08-06 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0014_soru_takip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MudahaleTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120, verbose_name='Ad')),
                ('ikon', models.CharField(blank=True, max_length=8, verbose_name='İkon')),
                ('renk', models.CharField(default='#2563EB', help_text='Hex renk kodu (#2563EB)', max_length=7, verbose_name='Renk')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('form_semasi', models.JSONField(blank=True, default=list, help_text='[{"key":"kaynak","label":"Kaynak","type":"text"}]', verbose_name='Ek form alanları')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Müdahale türü',
                'verbose_name_plural': 'Müdahale türleri',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='AkademikMudahale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konu', models.CharField(blank=True, max_length=200, verbose_name='Konu')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('sure_dakika', models.PositiveIntegerField(default=0, verbose_name='Süre (dk)')),
                ('degerlendirme_notu', models.TextField(blank=True, verbose_name='Değerlendirme notu (personel)')),
                ('veliye_goster', models.BooleanField(default=True, verbose_name='Veliye göster')),
                ('ek_alanlar', models.JSONField(blank=True, default=dict, verbose_name='Ek alanlar')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('ders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='akademik_mudahaleler', to='takip.ders', verbose_name='Ders')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_akademik_mudahaleler', to=settings.AUTH_USER_MODEL, verbose_name='Kaydı oluşturan')),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='akademik_mudahaleler', to='takip.talebe', verbose_name='Talebe')),
                ('mudahale_turu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kayitlar', to='takip.mudahaleturu', verbose_name='Müdahale türü')),
            ],
            options={
                'verbose_name': 'Akademik müdahale',
                'verbose_name_plural': 'Akademik müdahaleler',
                'ordering': ['-tarih', '-id'],
            },
        ),
    ]
