# Generated by Django 6.1 on 2026-08-06 22:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0015_akademik_mudahale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DenemeEslestirmeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_adi', models.CharField(max_length=200, unique=True, verbose_name='Excel ad soyad (normalize)')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deneme_eslestirme_aliaslari', to='takip.talebe', verbose_name='Talebe')),
            ],
            options={
                'verbose_name': 'Deneme eşleştirme alias',
                'verbose_name_plural': 'Deneme eşleştirme aliasları',
            },
        ),
        migrations.CreateModel(
            name='DenemeSinavi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Deneme adı')),
                ('sinav_tarihi', models.DateField(verbose_name='Sınav tarihi')),
                ('sinif_seviyesi', models.CharField(help_text='Örn. 6, 7, 8', max_length=30, verbose_name='Sınıf seviyesi')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('durum', models.CharField(choices=[('taslak', 'Taslak'), ('aktif', 'Aktif')], default='taslak', max_length=10, verbose_name='Durum')),
                ('yuklenme_zamani', models.DateTimeField(blank=True, null=True)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_denemeler', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('yukleyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yukledigi_denemeler', to=settings.AUTH_USER_MODEL, verbose_name='Excel yükleyen')),
            ],
            options={
                'verbose_name': 'Deneme sınavı',
                'verbose_name_plural': 'Deneme sınavları',
                'ordering': ['-sinav_tarihi', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DenemeSonucu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toplam_dogru', models.PositiveIntegerField(default=0)),
                ('toplam_yanlis', models.PositiveIntegerField(default=0)),
                ('toplam_bos', models.PositiveIntegerField(default=0)),
                ('toplam_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('puan', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('deneme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sonuclar', to='takip.denemesinavi', verbose_name='Deneme')),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deneme_sonuclari', to='takip.talebe', verbose_name='Talebe')),
            ],
            options={
                'verbose_name': 'Deneme sonucu',
                'verbose_name_plural': 'Deneme sonuçları',
                'ordering': ['-toplam_net', 'talebe__ad_soyad'],
            },
        ),
        migrations.CreateModel(
            name='DenemeBransSonucu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brans', models.CharField(choices=[('turkce', 'Türkçe'), ('matematik', 'Matematik'), ('fen', 'Fen Bilimleri'), ('sosyal', 'Sosyal Bilgiler'), ('din', 'Din Kültürü'), ('ingilizce', 'İngilizce')], max_length=20, verbose_name='Branş')),
                ('dogru', models.PositiveIntegerField(default=0)),
                ('yanlis', models.PositiveIntegerField(default=0)),
                ('bos', models.PositiveIntegerField(default=0)),
                ('net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('sonuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brans_satirlari', to='takip.denemesonucu', verbose_name='Sonuç')),
            ],
            options={
                'verbose_name': 'Deneme branş sonucu',
                'verbose_name_plural': 'Deneme branş sonuçları',
            },
        ),
        migrations.AddConstraint(
            model_name='denemesonucu',
            constraint=models.UniqueConstraint(fields=('deneme', 'talebe'), name='deneme_talebe_tek_sonuc'),
        ),
        migrations.AddConstraint(
            model_name='denemebranssonucu',
            constraint=models.UniqueConstraint(fields=('sonuc', 'brans'), name='deneme_sonuc_brans_benzersiz'),
        ),
    ]
