# Generated by Django 6.1 on 2026-08-06 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0016_deneme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtutHaftaPlani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hafta_baslangic', models.DateField(verbose_name='Hafta başlangıcı')),
                ('hafta_bitis', models.DateField(verbose_name='Hafta bitişi')),
                ('durum', models.CharField(choices=[('taslak', 'Taslak'), ('aktif', 'Aktif'), ('tamamlandi', 'Tamamlandı')], default='aktif', max_length=12, verbose_name='Durum')),
                ('notlar', models.TextField(blank=True, verbose_name='Haftalık not')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('etut_hocasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haftalik_planlar', to='takip.etuthocasi', verbose_name='Etüt hocası')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_etut_planlari', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Etüt hafta planı',
                'verbose_name_plural': 'Etüt hafta planları',
                'ordering': ['-hafta_baslangic', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EtutPlanFaaliyet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.PositiveSmallIntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], verbose_name='Gün')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('faaliyet_turu', models.CharField(choices=[('etut', 'Etüt çalışması'), ('brans_deneme', 'Branş denemesi'), ('ktt', 'KTT uygulaması'), ('ktt_analiz', 'KTT analizi'), ('deneme_analiz', 'Deneme analizi'), ('kitap_okuma', 'Kitap okuma'), ('konu_tekrar', 'Konu tekrarı'), ('soru_cozum', 'Soru çözümü'), ('akademik', 'Akademik müdahale'), ('video', 'Video destekli çalışma')], max_length=20, verbose_name='Faaliyet türü')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('hedef', models.CharField(blank=True, help_text='Örn. 40 soru, 20 sayfa', max_length=200, verbose_name='Hedef')),
                ('uygulama_durumu', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('devam', 'Devam ediyor'), ('tamamlandi', 'Tamamlandı'), ('yapilamadi', 'Yapılamadı')], default='bekliyor', max_length=12, verbose_name='Uygulama durumu')),
                ('tamamlanma_notu', models.TextField(blank=True, verbose_name='Tamamlanma notu')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faaliyetler', to='takip.etuthaftaplani', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Etüt plan faaliyeti',
                'verbose_name_plural': 'Etüt plan faaliyetleri',
                'ordering': ['gun', 'sira', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='etuthaftaplani',
            constraint=models.UniqueConstraint(fields=('etut_hocasi', 'hafta_baslangic'), name='etut_hoca_hafta_tek_plan'),
        ),
    ]
