# Generated by Django 6.1 on 2026-08-06 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0017_etut_plani'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiniDersTakipAlani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120, unique=True, verbose_name='Takip alanı')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dini ders takip alanı',
                'verbose_name_plural': 'Dini ders takip alanları',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.AddField(
            model_name='dinidersseviyesi',
            name='hocalar',
            field=models.ManyToManyField(blank=True, related_name='sorumlu_dini_ders_seviyeleri', to='takip.etuthocasi', verbose_name='Sorumlu hocalar'),
        ),
        migrations.CreateModel(
            name='DiniDersKonu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Konu')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('seviye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dini_ders_konulari', to='takip.dinidersseviyesi', verbose_name='Seviye')),
                ('alan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konular', to='takip.diniderstakipalani', verbose_name='Takip alanı')),
            ],
            options={
                'verbose_name': 'Dini ders konusu',
                'verbose_name_plural': 'Dini ders konuları',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='DiniDersKonuKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamamlandi', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('personel_notu', models.TextField(blank=True, verbose_name='Not (personel)')),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('isaretleyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dini_ders_isaretleri', to=settings.AUTH_USER_MODEL, verbose_name='İşaretleyen')),
                ('konu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kayitlar', to='takip.diniderskonu', verbose_name='Konu')),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dini_ders_konu_kayitlari', to='takip.talebe', verbose_name='Talebe')),
            ],
            options={
                'verbose_name': 'Dini ders konu kaydı',
                'verbose_name_plural': 'Dini ders konu kayıtları',
                'constraints': [models.UniqueConstraint(fields=('talebe', 'konu'), name='dini_ders_talebe_konu_benzersiz')],
            },
        ),
        migrations.AddConstraint(
            model_name='diniderskonu',
            constraint=models.UniqueConstraint(fields=('alan', 'seviye', 'ad'), name='dini_ders_alan_seviye_konu_benzersiz'),
        ),
    ]
