# Generated by Django 6.1 on 2026-08-06 22:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0020_namaz_yoklama'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OgretmenOdemeDonemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('baslangic', models.DateField(verbose_name='Başlangıç')),
                ('bitis', models.DateField(verbose_name='Bitiş')),
                ('saatlik_ucret', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Saatlik ücret (dönem)')),
                ('toplam_saat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Toplam ders saati')),
                ('odenecek_tutar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Ödenecek tutar')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('etut_hocasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='odeme_donemleri', to='takip.etuthocasi', verbose_name='Öğretmen')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_olusturdu', to=settings.AUTH_USER_MODEL)),
                ('son_duzenleyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_duzenledi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Öğretmen ödeme dönemi',
                'verbose_name_plural': 'Öğretmen ödeme dönemleri',
                'ordering': ['-baslangic', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OgretmenOdemeGunKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('toplam_saat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Günlük toplam saat')),
                ('donem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gunler', to='takip.ogretmenodemedonemi', verbose_name='Dönem')),
            ],
            options={
                'verbose_name': 'Ödeme gün kaydı',
                'verbose_name_plural': 'Ödeme gün kayıtları',
                'ordering': ['tarih'],
            },
        ),
        migrations.CreateModel(
            name='OgretmenOdemeDersKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saat', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ders saati')),
                ('brans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ogretmen_odeme_dersleri', to='takip.brans', verbose_name='Branş')),
                ('sinif_sube', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ogretmen_odeme_dersleri', to='takip.sinifsube', verbose_name='Sınıf')),
                ('gun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dersler', to='takip.ogretmenodemegunkaydi', verbose_name='Gün')),
            ],
            options={
                'verbose_name': 'Ödeme ders kaydı',
                'verbose_name_plural': 'Ödeme ders kayıtları',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OgretmenOdemeProfili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saatlik_ucret', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Saatlik ücret')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('brans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ogretmen_odeme_profilleri', to='takip.brans', verbose_name='Branş')),
                ('etut_hocasi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odeme_profili', to='takip.etuthocasi', verbose_name='Etüt hocası')),
            ],
            options={
                'verbose_name': 'Öğretmen ödeme profili',
                'verbose_name_plural': 'Öğretmen ödeme profilleri',
            },
        ),
        migrations.AddConstraint(
            model_name='ogretmenodemedonemi',
            constraint=models.CheckConstraint(condition=models.Q(('bitis__gte', models.F('baslangic'))), name='ogretmen_odeme_donem_tarih_sirasi'),
        ),
        migrations.AddConstraint(
            model_name='ogretmenodemegunkaydi',
            constraint=models.UniqueConstraint(fields=('donem', 'tarih'), name='ogretmen_odeme_gun_benzersiz'),
        ),
    ]
