# Generated by Django 6.1 on 2026-08-06 23:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0021_ogretmen_odeme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OgretmenSinavNotu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('yazili', 'Yazılı'), ('sozlu', 'Sözlü')], default='yazili', max_length=10, verbose_name='Tür')),
                ('puan', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Puan')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('veliye_goster', models.BooleanField(default=True, verbose_name='Veliye göster')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ogretmen_sinav_notlari', to='takip.ders', verbose_name='Ders')),
                ('etut_hocasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='girdigi_sinav_notlari', to='takip.etuthocasi', verbose_name='Etüt hocası')),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogretmen_sinav_notlari', to='takip.talebe', verbose_name='Talebe')),
            ],
            options={
                'verbose_name': 'Öğretmen sınav notu',
                'verbose_name_plural': 'Öğretmen sınav notları',
                'ordering': ['-tarih', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TalebeEvGunu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(help_text='0=Pazartesi … 6=Pazar', verbose_name='Haftanın günü')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Talebe ev günü',
                'verbose_name_plural': 'Talebe ev günleri',
                'ordering': ['weekday'],
                'constraints': [models.UniqueConstraint(fields=('weekday',), name='benzersiz_talebe_ev_gunu')],
            },
        ),
        migrations.CreateModel(
            name='TalebeHesap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('talebe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talebe_hesabi', to='takip.talebe', verbose_name='Talebe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talebe_hesabi', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı hesabı')),
            ],
            options={
                'verbose_name': 'Talebe hesabı',
                'verbose_name_plural': 'Talebe hesapları',
            },
        ),
        migrations.CreateModel(
            name='YaziliKamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Kamp adı')),
                ('baslangic', models.DateField(verbose_name='Başlangıç tarihi')),
                ('bitis', models.DateField(verbose_name='Bitiş tarihi')),
                ('sinif_seviyesi', models.CharField(help_text='Örn. 6, 7, 8', max_length=30, verbose_name='Sınıf seviyesi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('veli_goster', models.BooleanField(default=True, verbose_name='Veli panelinde göster')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_yazili_kamplar', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Yazılı kamp',
                'verbose_name_plural': 'Yazılı kamplar',
                'ordering': ['-baslangic', '-id'],
            },
        ),
        migrations.CreateModel(
            name='YaziliSinav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Sınav adı')),
                ('sinav_tarihi', models.DateField(verbose_name='Sınav tarihi')),
                ('ders_ad', models.CharField(max_length=120, verbose_name='Ders')),
                ('brans', models.CharField(blank=True, max_length=80, verbose_name='Branş')),
                ('soru_sayisi', models.PositiveIntegerField(verbose_name='Soru sayısı')),
                ('durum', models.CharField(choices=[('taslak', 'Taslak'), ('aktif', 'Aktif')], default='taslak', max_length=10, verbose_name='Durum')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('kamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinavlar', to='takip.yazilikamp', verbose_name='Kamp')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_yazili_sinavlar', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Yazılı sınav',
                'verbose_name_plural': 'Yazılı sınavlar',
                'ordering': ['sinav_tarihi', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TalebeKonumKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('mod', models.CharField(choices=[('kurs', 'Kurs'), ('ev', 'Ev'), ('izin', 'İzin')], max_length=10, verbose_name='Konum')),
                ('aciklama', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konum_kayitlari', to='takip.talebe', verbose_name='Talebe')),
            ],
            options={
                'verbose_name': 'Talebe konum kaydı',
                'verbose_name_plural': 'Talebe konum kayıtları',
                'ordering': ['-tarih', '-id'],
                'constraints': [models.UniqueConstraint(fields=('talebe', 'tarih'), name='benzersiz_talebe_konum_tarih')],
            },
        ),
        migrations.CreateModel(
            name='YaziliSonuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogru', models.PositiveIntegerField(default=0, verbose_name='Doğru')),
                ('yanlis', models.PositiveIntegerField(default=0, verbose_name='Yanlış')),
                ('bos', models.PositiveIntegerField(default=0, verbose_name='Boş')),
                ('net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=8, verbose_name='Net')),
                ('puan', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5, verbose_name='Puan (100)')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('kaydeden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaydettigi_yazili_sonuclar', to=settings.AUTH_USER_MODEL, verbose_name='Kaydeden')),
                ('sinav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sonuclar', to='takip.yazilisinav', verbose_name='Sınav')),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yazili_sonuclari', to='takip.talebe', verbose_name='Talebe')),
            ],
            options={
                'verbose_name': 'Yazılı sonuç',
                'verbose_name_plural': 'Yazılı sonuçlar',
                'ordering': ['-puan', '-net', 'talebe__ad_soyad'],
                'constraints': [models.UniqueConstraint(fields=('sinav', 'talebe'), name='yazili_sinav_talebe_tek_sonuc')],
            },
        ),
    ]
