# Generated by Django 6.1 on 2026-08-06 23:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0022_talebe_panel_ogretmen_not'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisiplinOlayTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120, verbose_name='Ad')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disiplin olay türü',
                'verbose_name_plural': 'Disiplin olay türleri',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='GorusmeTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120, verbose_name='Ad')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Görüşme türü',
                'verbose_name_plural': 'Görüşme türleri',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='AidatTanim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120, verbose_name='Ad')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Tutar')),
                ('vade', models.DateField(verbose_name='Vade')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('egitim_yili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aidat_tanimlari', to='takip.egitimyili', verbose_name='Eğitim yılı')),
            ],
            options={
                'verbose_name': 'Aidat tanımı',
                'verbose_name_plural': 'Aidat tanımları',
                'ordering': ['-vade', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='DisiplinKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('sonuc', models.TextField(blank=True, verbose_name='Sonuç')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disiplin_kayitlari', to='takip.talebe', verbose_name='Talebe')),
                ('tur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kayitlar', to='takip.disiplinolayturu', verbose_name='Olay türü')),
            ],
            options={
                'verbose_name': 'Disiplin kaydı',
                'verbose_name_plural': 'Disiplin kayıtları',
                'ordering': ['-tarih', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MezunProfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mezuniyet_yili', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mezuniyet yılı')),
                ('mezuniyet_tarihi', models.DateField(blank=True, null=True, verbose_name='Mezuniyet tarihi')),
                ('lgs_puani', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='LGS puanı')),
                ('lgs_sira', models.PositiveIntegerField(blank=True, null=True, verbose_name='LGS sıra')),
                ('yerlestigi_lise', models.CharField(blank=True, max_length=200, verbose_name='Yerleştiği lise')),
                ('yks_puani', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='YKS puanı')),
                ('iletisim_telefon', models.CharField(blank=True, max_length=20, verbose_name='İletişim telefonu')),
                ('iletisim_eposta', models.EmailField(blank=True, max_length=254, verbose_name='İletişim e-posta')),
                ('iletisim_adres', models.TextField(blank=True, verbose_name='İletişim adresi')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('donem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mezun_profilleri', to='takip.donem', verbose_name='Dönem')),
                ('talebe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mezun_profili', to='takip.talebe', verbose_name='Talebe')),
            ],
            options={
                'verbose_name': 'Mezun profili',
                'verbose_name_plural': 'Mezun profilleri',
                'ordering': ['-mezuniyet_tarihi', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OgrenciGorusmesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('ozet', models.CharField(max_length=200, verbose_name='Özet')),
                ('detay', models.TextField(blank=True, verbose_name='Detay')),
                ('kararlar', models.TextField(blank=True, verbose_name='Kararlar')),
                ('veli_goster', models.BooleanField(default=False, verbose_name='Veliye göster')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehberlik_gorusmeleri', to='takip.talebe', verbose_name='Talebe')),
                ('tur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gorusmeler', to='takip.gorusmeturu', verbose_name='Görüşme türü')),
            ],
            options={
                'verbose_name': 'Öğrenci görüşmesi',
                'verbose_name_plural': 'Öğrenci görüşmeleri',
                'ordering': ['-tarih', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TalebeAidatKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('odendi', 'Ödendi'), ('kismi', 'Kısmi'), ('gecikmis', 'Gecikmiş'), ('muaf', 'Muaf')], default='bekliyor', max_length=10, verbose_name='Durum')),
                ('odenen_tutar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Ödenen tutar')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aidat_kayitlari', to='takip.talebe', verbose_name='Talebe')),
                ('tanim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kayitlar', to='takip.aidattanim', verbose_name='Aidat tanımı')),
            ],
            options={
                'verbose_name': 'Talebe aidat kaydı',
                'verbose_name_plural': 'Talebe aidat kayıtları',
                'ordering': ['-tanim__vade', 'talebe__ad_soyad'],
            },
        ),
        migrations.CreateModel(
            name='AidatTahsilat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tutar')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('kaydeden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaydettigi_aidat_tahsilatlari', to=settings.AUTH_USER_MODEL, verbose_name='Kaydeden')),
                ('kayit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tahsilatlar', to='takip.talebeaidatkaydi', verbose_name='Aidat kaydı')),
            ],
            options={
                'verbose_name': 'Aidat tahsilat',
                'verbose_name_plural': 'Aidat tahsilatları',
                'ordering': ['-tarih', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GunlukTakipKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('devam', models.CharField(choices=[('geldi', 'Geldi'), ('gec', 'Geç'), ('gelmedi', 'Gelmedi')], default='geldi', max_length=10, verbose_name='Devam')),
                ('etut_katilim', models.BooleanField(default=True, verbose_name='Etüt katılım')),
                ('not_alani', models.TextField(blank=True, verbose_name='Not')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gunluk_takip_kayitlari', to='takip.talebe', verbose_name='Talebe')),
            ],
            options={
                'verbose_name': 'Günlük takip kaydı',
                'verbose_name_plural': 'Günlük takip kayıtları',
                'ordering': ['-tarih', 'talebe__ad_soyad'],
                'constraints': [models.UniqueConstraint(fields=('talebe', 'tarih'), name='benzersiz_gunluk_takip_talebe_tarih')],
            },
        ),
        migrations.AddConstraint(
            model_name='talebeaidatkaydi',
            constraint=models.UniqueConstraint(fields=('tanim', 'talebe'), name='benzersiz_talebe_aidat_tanim'),
        ),
    ]
