# Generated by Django 6.1 on 2026-08-07 03:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0026_imam_muezzin_havuz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ogrencigorusmesi',
            options={'ordering': ['-tarih', '-saat', '-id'], 'verbose_name': 'Öğrenci görüşmesi', 'verbose_name_plural': 'Öğrenci görüşmeleri'},
        ),
        migrations.CreateModel(
            name='DershaneProgrami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Program adı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('baslangic_tarihi', models.DateField(verbose_name='Başlangıç tarihi')),
                ('bitis_tarihi', models.DateField(verbose_name='Bitiş tarihi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('surum_no', models.PositiveIntegerField(default=1, verbose_name='Sürüm no')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_dershane_programlari', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Dershane programı',
                'verbose_name_plural': 'Dershane programları',
                'ordering': ['-baslangic_tarihi', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DershaneEtutGrubu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiket', models.CharField(max_length=120, verbose_name='Etüt grubu')),
                ('sinif_seviye', models.CharField(max_length=10, verbose_name='Sınıf seviyesi')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('etut_hocasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dershane_gruplari', to='takip.etuthocasi', verbose_name='Etüt hocası')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etut_gruplari', to='takip.dershaneprogrami', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Dershane etüt grubu',
                'verbose_name_plural': 'Dershane etüt grupları',
                'ordering': ['sira', 'etiket'],
            },
        ),
        migrations.CreateModel(
            name='DershaneProgramSablon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Şablon adı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('veri', models.JSONField(default=dict, verbose_name='Program verisi')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dershane_sablonlari', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Dershane program şablonu',
                'verbose_name_plural': 'Dershane program şablonları',
                'ordering': ['-olusturulma', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='DershaneSaatBloku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.PositiveSmallIntegerField(verbose_name='Gün (0=Pzt)')),
                ('baslangic_saati', models.TimeField(verbose_name='Başlangıç')),
                ('bitis_saati', models.TimeField(verbose_name='Bitiş')),
                ('tur', models.CharField(choices=[('ders', 'Ders'), ('namaz', 'Namaz'), ('yemek', 'Yemek'), ('mola', 'Mola'), ('etut', 'Etüt'), ('rehberlik', 'Rehberlik')], default='ders', max_length=16, verbose_name='Tür')),
                ('aciklama', models.CharField(max_length=200, verbose_name='Açıklama')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saat_bloklari', to='takip.dershaneprogrami', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Dershane saat bloğu',
                'verbose_name_plural': 'Dershane saat blokları',
                'ordering': ['gun', 'sira', 'baslangic_saati', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DershaneProgramGun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.PositiveSmallIntegerField(verbose_name='Gün (0=Pzt)')),
                ('durum', models.CharField(choices=[('bos', 'Boş'), ('duzenleniyor', 'Düzenleniyor'), ('tamamlandi', 'Tamamlandı')], default='bos', max_length=16, verbose_name='Durum')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gunler', to='takip.dershaneprogrami', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Dershane program günü',
                'verbose_name_plural': 'Dershane program günleri',
                'ordering': ['gun'],
                'constraints': [models.UniqueConstraint(fields=('program', 'gun'), name='dershane_program_gun_tek')],
            },
        ),
        migrations.CreateModel(
            name='DershaneProgramSurum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surum_no', models.PositiveIntegerField(verbose_name='Sürüm no')),
                ('etiket', models.CharField(max_length=120, verbose_name='Etiket')),
                ('veri', models.JSONField(default=dict, verbose_name='Anlık görüntü')),
                ('olusturulma', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturulma')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dershane_surumleri', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surumler', to='takip.dershaneprogrami', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Dershane program sürümü',
                'verbose_name_plural': 'Dershane program sürümleri',
                'ordering': ['-surum_no', '-id'],
                'constraints': [models.UniqueConstraint(fields=('program', 'surum_no'), name='dershane_surum_tek')],
            },
        ),
        migrations.CreateModel(
            name='DershaneDersAtamasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders_adi', models.CharField(blank=True, max_length=120, verbose_name='Ders adı')),
                ('ogretmen_adi', models.CharField(blank=True, max_length=120, verbose_name='Öğretmen adı')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('ders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dershane_atamalari', to='takip.ders', verbose_name='Ders')),
                ('ogretmen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dershane_atamalari', to='takip.personelprofili', verbose_name='Öğretmen')),
                ('etut_grubu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atamalar', to='takip.dershaneetutgrubu', verbose_name='Etüt grubu')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ders_atamalari', to='takip.dershaneprogrami', verbose_name='Program')),
                ('saat_bloku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atamalar', to='takip.dershanesaatbloku', verbose_name='Saat bloğu')),
            ],
            options={
                'verbose_name': 'Dershane ders ataması',
                'verbose_name_plural': 'Dershane ders atamaları',
                'constraints': [models.UniqueConstraint(fields=('saat_bloku', 'etut_grubu'), name='dershane_atama_tek')],
            },
        ),
    ]
