# Generated by Django 6.1 on 2026-08-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0027_dershane_programi'),
    ]

    operations = [
        migrations.AddField(
            model_name='duyuru',
            name='gorsel',
            field=models.ImageField(blank=True, help_text='Sol tarafta gösterilecek fotoğraf.', null=True, upload_to='duyurular/', verbose_name='Görsel'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='video_dosya',
            field=models.FileField(blank=True, help_text='İsteğe bağlı. Yüklenen video sol tarafta oynatılır.', null=True, upload_to='duyurular/videolar/', verbose_name='Video dosyası'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, Vimeo veya doğrudan .mp4 bağlantısı.', verbose_name='Video bağlantısı'),
        ),
    ]
