# Generated by Django 6.1 on 2026-08-07 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0028_duyuru_medya'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisiplinKurulKarar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karar_no', models.CharField(max_length=40, unique=True, verbose_name='Karar no')),
                ('metin', models.TextField(verbose_name='Karar metni')),
                ('kategori', models.CharField(choices=[('akademik', 'Akademik'), ('davranis', 'Davranış'), ('dini', 'Dini Eğitim'), ('rehberlik', 'Rehberlik'), ('disiplin', 'Disiplin'), ('yoklama', 'Yoklama'), ('veli', 'Veli Görüşmesi')], default='disiplin', max_length=16, verbose_name='Kategori')),
                ('baslangic_tarihi', models.DateField(blank=True, null=True, verbose_name='Başlangıç')),
                ('kontrol_tarihi', models.DateField(blank=True, null=True, verbose_name='Kontrol tarihi')),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('uygulaniyor', 'Uygulanıyor'), ('kontrol', 'Kontrol Bekliyor'), ('tamamlandi', 'Tamamlandı'), ('gecikti', 'Gecikti')], default='bekliyor', max_length=16, verbose_name='Durum')),
                ('iliskili_modul', models.CharField(choices=[('yok', 'Bağlantı Yok'), ('akademik_takip', 'Akademik Takip'), ('rehberlik', 'Rehberlik'), ('dini_ders', 'Dini Ders'), ('yoklama', 'Yoklama'), ('gorevler', 'Görevler')], default='yok', max_length=20, verbose_name='İlişkili modül')),
                ('iliskili_kayit_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='İlişkili kayıt ID')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('arsivlandi', models.BooleanField(default=False, verbose_name='Arşivlendi')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_kurul_kararlari', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('son_duzenleyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duzenledigi_kurul_kararlari', to=settings.AUTH_USER_MODEL, verbose_name='Son düzenleyen')),
                ('sorumlu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorumlu_oldugu_kurul_kararlari', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu personel')),
            ],
            options={
                'verbose_name': 'Kurul kararı',
                'verbose_name_plural': 'Kurul kararları',
                'ordering': ['karar_no'],
            },
        ),
        migrations.CreateModel(
            name='DisiplinKurulKararNot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metin', models.TextField(verbose_name='Not')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('karar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takip_notlari', to='takip.disiplinkurulkarar', verbose_name='Karar')),
                ('yazar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kurul_karar_notlari', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'verbose_name': 'Karar takip notu',
                'verbose_name_plural': 'Karar takip notları',
                'ordering': ['-olusturulma'],
            },
        ),
        migrations.CreateModel(
            name='DisiplinKurulKararTakip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adim', models.CharField(choices=[('olusturuldu', 'Karar oluşturuldu'), ('personel', 'Personel atandı'), ('not', 'Not eklendi'), ('kontrol', 'Kontrol edildi'), ('tamamlandi', 'Tamamlandı')], max_length=16, verbose_name='Adım')),
                ('aciklama', models.CharField(blank=True, max_length=240, verbose_name='Açıklama')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('karar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takip_adimlari', to='takip.disiplinkurulkarar', verbose_name='Karar')),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kurul_karar_takip_adimlari', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Karar takip adımı',
                'verbose_name_plural': 'Karar takip adımları',
                'ordering': ['olusturulma', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DisiplinKurulu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurul_no', models.CharField(max_length=32, unique=True, verbose_name='Kurul no')),
                ('kurul_turu', models.CharField(choices=[('disiplin', 'Disiplin Kurulu'), ('degerlendirme', 'Değerlendirme Kurulu'), ('akademik', 'Akademik Kurul'), ('rehberlik', 'Rehberlik Kurulu')], default='disiplin', max_length=24, verbose_name='Kurul türü')),
                ('durum', models.CharField(choices=[('taslak', 'Taslak'), ('acildi', 'Kurul Açıldı'), ('toplanti', 'Toplantı Yapıldı'), ('kararlar', 'Kararlar Belirlendi'), ('uygulama', 'Uygulama Süreci'), ('kontrol', 'Kontrol Toplantısı'), ('sonuclandi', 'Sonuçlandırıldı')], default='taslak', max_length=16, verbose_name='Durum')),
                ('toplanti_tarihi', models.DateField(blank=True, null=True, verbose_name='Toplantı tarihi')),
                ('toplanti_saati', models.TimeField(blank=True, null=True, verbose_name='Toplantı saati')),
                ('toplanti_yeri', models.CharField(blank=True, max_length=200, verbose_name='Toplantı yeri')),
                ('genel_aciklama', models.TextField(blank=True, verbose_name='Genel açıklama')),
                ('genel_degerlendirme', models.TextField(blank=True, verbose_name='Genel değerlendirme')),
                ('sonuc_metni', models.TextField(blank=True, verbose_name='Sonuç')),
                ('sonraki_kontrol_tarihi', models.DateField(blank=True, null=True, verbose_name='Sonraki kontrol tarihi')),
                ('tutanak_pdf', models.FileField(blank=True, null=True, upload_to='disiplin_kurul/tutanaklar/', verbose_name='Tutanak PDF')),
                ('arsivlandi', models.BooleanField(default=False, verbose_name='Arşivlendi')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_disiplin_kurullari', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('oturum_baskani', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baskanlik_ettigi_kurullar', to=settings.AUTH_USER_MODEL, verbose_name='Oturum başkanı')),
                ('raportor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raportorluk_ettigi_kurullar', to=settings.AUTH_USER_MODEL, verbose_name='Raportör')),
                ('son_duzenleyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duzenledigi_disiplin_kurullari', to=settings.AUTH_USER_MODEL, verbose_name='Son düzenleyen')),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disiplin_kurullari', to='takip.talebe', verbose_name='Talebe')),
            ],
            options={
                'verbose_name': 'Disiplin kurulu',
                'verbose_name_plural': 'Disiplin kurulları',
                'ordering': ['-toplanti_tarihi', '-id'],
            },
        ),
        migrations.AddField(
            model_name='disiplinkurulkarar',
            name='kurul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kararlar', to='takip.disiplinkurulu', verbose_name='Kurul'),
        ),
        migrations.CreateModel(
            name='DisiplinKurulGundem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira', models.PositiveSmallIntegerField(default=1, verbose_name='Sıra')),
                ('baslik', models.CharField(max_length=240, verbose_name='Madde')),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('goruldu', 'Görüşüldü')], default='bekliyor', max_length=12, verbose_name='Durum')),
                ('kurul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gundem_maddeleri', to='takip.disiplinkurulu', verbose_name='Kurul')),
            ],
            options={
                'verbose_name': 'Gündem maddesi',
                'verbose_name_plural': 'Gündem maddeleri',
                'ordering': ['sira', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DisiplinKurulKatilimci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurum_gorevi', models.CharField(blank=True, max_length=120, verbose_name='Kurumdaki görevi')),
                ('kurul_gorevi', models.CharField(choices=[('baskan', 'Kurul Başkanı'), ('raportor', 'Raportör'), ('uye', 'Kurul Üyesi'), ('danisman', 'Danışman'), ('gozlemci', 'Gözlemci')], default='uye', max_length=16, verbose_name='Kuruldaki görevi')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disiplin_kurul_katilimlari', to='takip.personelprofili', verbose_name='Personel')),
                ('kurul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='katilimcilar', to='takip.disiplinkurulu', verbose_name='Kurul')),
            ],
            options={
                'verbose_name': 'Kurul katılımcısı',
                'verbose_name_plural': 'Kurul katılımcıları',
                'ordering': ['sira', 'id'],
                'constraints': [models.UniqueConstraint(fields=('kurul', 'personel'), name='disiplin_kurul_katilimci_tek')],
            },
        ),
    ]
