# Generated by Django 6.1 on 2026-08-07 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0029_disiplin_kurulu'),
    ]

    operations = [
        migrations.CreateModel(
            name='DershaneGrupDersOgretmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dershane_grup_ogretmenleri', to='takip.ders', verbose_name='Ders')),
                ('etut_grubu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ders_ogretmenleri', to='takip.dershaneetutgrubu', verbose_name='Etüt grubu')),
                ('ogretmen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dershane_grup_dersleri', to='takip.personelprofili', verbose_name='Öğretmen')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grup_ders_ogretmenleri', to='takip.dershaneprogrami', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Grup ders öğretmeni',
                'verbose_name_plural': 'Grup ders öğretmenleri',
                'constraints': [models.UniqueConstraint(fields=('program', 'etut_grubu', 'ders'), name='dershane_grup_ders_ogretmen_tek')],
            },
        ),
    ]
