# Generated by Django 6.1 on 2026-08-07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takip", "0030_dershane_grup_ders_ogretmen"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EtutFaaliyetHavuzu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=120, verbose_name="Başlık")),
                ("aciklama", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "varsayilan_hedef",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Varsayılan hedef"
                    ),
                ),
                (
                    "renk",
                    models.CharField(
                        default="#eff6ff", max_length=20, verbose_name="Renk"
                    ),
                ),
                (
                    "ikon",
                    models.CharField(blank=True, max_length=8, verbose_name="İkon"),
                ),
                ("sira", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "ozel",
                    models.BooleanField(
                        default=False,
                        help_text="True ise yalnızca ilgili hocanın havuzunda görünür.",
                        verbose_name="Hocaya özel",
                    ),
                ),
                ("olusturulma", models.DateTimeField(auto_now_add=True)),
                (
                    "etut_hocasi",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ozel_faaliyet_havuzu",
                        to="takip.etuthocasi",
                        verbose_name="Etüt hocası",
                    ),
                ),
                (
                    "olusturan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="olusturdugu_etut_havuz_kartlari",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etüt faaliyet havuzu",
                "verbose_name_plural": "Etüt faaliyet havuzu",
                "ordering": ["sira", "baslik"],
            },
        ),
        migrations.CreateModel(
            name="EtutGrupSaatBloku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gun",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Pazartesi"),
                            (1, "Salı"),
                            (2, "Çarşamba"),
                            (3, "Perşembe"),
                            (4, "Cuma"),
                            (5, "Cumartesi"),
                            (6, "Pazar"),
                        ],
                        verbose_name="Gün",
                    ),
                ),
                ("baslangic_saati", models.TimeField(verbose_name="Başlangıç")),
                ("bitis_saati", models.TimeField(verbose_name="Bitiş")),
                ("sira", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                ("olusturulma", models.DateTimeField(auto_now_add=True)),
                ("guncellenme", models.DateTimeField(auto_now=True)),
                (
                    "etut_hocasi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etut_saat_bloklari",
                        to="takip.etuthocasi",
                        verbose_name="Etüt hocası / grup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Etüt saat bloğu",
                "verbose_name_plural": "Etüt saat blokları",
                "ordering": ["etut_hocasi", "gun", "sira", "baslangic_saati"],
            },
        ),
        migrations.AddField(
            model_name="etutplanfaaliyet",
            name="havuz",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plan_atamalari",
                to="takip.etutfaaliyethavuzu",
                verbose_name="Havuz kartı",
            ),
        ),
        migrations.AddField(
            model_name="etutplanfaaliyet",
            name="renk",
            field=models.CharField(
                blank=True, default="#eff6ff", max_length=20, verbose_name="Renk"
            ),
        ),
        migrations.AddField(
            model_name="etutplanfaaliyet",
            name="saat_bloku",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan_faaliyetleri",
                to="takip.etutgrupsaatbloku",
                verbose_name="Saat bloğu",
            ),
        ),
        migrations.AddConstraint(
            model_name="etutgrupsaatbloku",
            constraint=models.UniqueConstraint(
                fields=("etut_hocasi", "gun", "baslangic_saati"),
                name="etut_saat_blok_tek",
            ),
        ),
        migrations.AddConstraint(
            model_name="etutplanfaaliyet",
            constraint=models.UniqueConstraint(
                condition=models.Q(("saat_bloku__isnull", False)),
                fields=("plan", "saat_bloku"),
                name="etut_plan_saat_tek_faaliyet",
            ),
        ),
    ]
