# Generated by Django 6.1 on 2026-08-07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("takip", "0031_etut_plan_v2"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisiplinKurulAyar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kurul_adi",
                    models.CharField(
                        default="İstişare ve Disiplin Kurulu",
                        max_length=160,
                        verbose_name="Kurul adı",
                    ),
                ),
                (
                    "varsayilan_toplanti_yeri",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Varsayılan toplantı yeri"
                    ),
                ),
                ("guncellenme", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kurul ayarı",
                "verbose_name_plural": "Kurul ayarları",
            },
        ),
        migrations.CreateModel(
            name="DisiplinKurulVarsayilanGundem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=240, verbose_name="Madde")),
                ("sira", models.PositiveSmallIntegerField(default=1, verbose_name="Sıra")),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                ("olusturulma", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Varsayılan gündem maddesi",
                "verbose_name_plural": "Varsayılan gündem maddeleri",
                "ordering": ["sira", "id"],
            },
        ),
        migrations.CreateModel(
            name="DisiplinKurulVarsayilanUye",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kurul_gorevi",
                    models.CharField(
                        choices=[
                            ("baskan", "Kurul Başkanı"),
                            ("raportor", "Raportör"),
                            ("uye", "Kurul Üyesi"),
                            ("danisman", "Danışman"),
                            ("gozlemci", "Gözlemci"),
                        ],
                        default="uye",
                        max_length=16,
                        verbose_name="Kuruldaki görevi",
                    ),
                ),
                ("sira", models.PositiveSmallIntegerField(default=0, verbose_name="Sıra")),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                ("olusturulma", models.DateTimeField(auto_now_add=True)),
                (
                    "personel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="varsayilan_kurul_uyelikleri",
                        to="takip.personelprofili",
                        verbose_name="Personel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Varsayılan kurul üyesi",
                "verbose_name_plural": "Varsayılan kurul üyeleri",
                "ordering": ["sira", "id"],
            },
        ),
        migrations.AlterField(
            model_name="disiplinkurulu",
            name="kurul_turu",
            field=models.CharField(
                choices=[
                    ("istisare_disiplin", "İstişare ve Disiplin Kurulu"),
                    ("disiplin", "Disiplin Kurulu"),
                    ("degerlendirme", "Değerlendirme Kurulu"),
                    ("akademik", "Akademik Kurul"),
                    ("rehberlik", "Rehberlik Kurulu"),
                ],
                default="istisare_disiplin",
                max_length=24,
                verbose_name="Kurul türü",
            ),
        ),
        migrations.AddConstraint(
            model_name="disiplinkurulvarsayilanuye",
            constraint=models.UniqueConstraint(
                fields=("personel",), name="disiplin_kurul_varsayilan_uye_tek"
            ),
        ),
    ]
