# Generated by Django 6.1 on 2026-08-07 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0032_disiplin_kurul_sablon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etutplanfaaliyet',
            name='faaliyet_turu',
            field=models.CharField(choices=[('etut', 'Etüt çalışması'), ('brans_deneme', 'Branş denemesi'), ('ktt', 'KTT uygulaması'), ('ktt_analiz', 'KTT analizi'), ('deneme_analiz', 'Deneme analizi'), ('kitap_okuma', 'Kitap okuma'), ('konu_tekrar', 'Konu tekrarı'), ('soru_cozum', 'Soru çözümü'), ('akademik', 'Akademik müdahale'), ('video', 'Video destekli çalışma')], default='etut', max_length=20, verbose_name='Faaliyet türü'),
        ),
        migrations.CreateModel(
            name='VeliIcerikGoruntuleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('sayfa', 'Sayfa'), ('duyuru', 'Duyuru'), ('ktt', 'KTT'), ('deneme', 'Deneme'), ('yazili', 'Yazılı'), ('dini_ders', 'Dini Ders'), ('aidat', 'Aidat')], max_length=20)),
                ('referans_id', models.PositiveIntegerField(default=0, help_text='İçerik birincil anahtarı; sayfa kayıtları için 0.')),
                ('sayfa', models.CharField(blank=True, max_length=80)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('ilk_goruntulenme', models.DateTimeField(auto_now_add=True)),
                ('son_goruntulenme', models.DateTimeField(auto_now=True)),
                ('talebe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veli_icerik_goruntulemeleri', to='takip.talebe')),
                ('veli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icerik_goruntulemeleri', to='takip.velihesap')),
            ],
            options={
                'verbose_name': 'Veli içerik görüntüleme',
                'verbose_name_plural': 'Veli içerik görüntülemeleri',
                'indexes': [models.Index(fields=['veli', 'tur'], name='takip_velii_veli_id_a4ee06_idx'), models.Index(fields=['veli', 'son_goruntulenme'], name='takip_velii_veli_id_9cca6b_idx')],
                'constraints': [models.UniqueConstraint(fields=('veli', 'talebe', 'tur', 'referans_id'), name='uniq_veli_icerik_goruntuleme')],
            },
        ),
    ]
