# Generated by Django 6.1 on 2026-08-07

from django.db import migrations, models


ILETISIM_GRUPLAR = {"veli", "ogrenci", "telefon", "whatsapp"}


def gorusme_turlerini_ayir(apps, schema_editor):
    GorusmeTuru = apps.get_model("takip", "GorusmeTuru")
    for tur in GorusmeTuru.objects.all():
        if tur.grup in ILETISIM_GRUPLAR:
            tur.alan = "iletisim"
        else:
            tur.alan = "rehberlik"
        tur.save(update_fields=["alan"])


class Migration(migrations.Migration):

    dependencies = [
        ("takip", "0033_veli_goruntuleme"),
    ]

    operations = [
        migrations.AddField(
            model_name="gorusmeturu",
            name="alan",
            field=models.CharField(
                choices=[
                    ("rehberlik", "Rehberlik"),
                    ("iletisim", "Veli & Talebe İletişim"),
                ],
                default="rehberlik",
                max_length=20,
                verbose_name="Bölüm",
            ),
        ),
        migrations.RunPython(gorusme_turlerini_ayir, migrations.RunPython.noop),
    ]
