# Generated by Django 6.1 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takip", "0034_gorusme_alan_ayrimi"),
    ]

    operations = [
        migrations.AddField(
            model_name="talebegeneldurum",
            name="durum_kodu",
            field=models.CharField(
                choices=[
                    ("iyi", "Çok iyi"),
                    ("takip", "Takip ediliyor"),
                    ("risk", "Riskli"),
                    ("pasif", "Pasif"),
                ],
                default="takip",
                max_length=12,
                verbose_name="Genel durum",
            ),
        ),
    ]
