# Generated by Django 6.1 on 2026-08-07 04:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0036_temizlik_mahal_sorumlusu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinansIndirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.SlugField(max_length=40, unique=True, verbose_name='Kod')),
                ('ad', models.CharField(max_length=80, verbose_name='Ad')),
                ('tur', models.CharField(choices=[('yuzde', 'Yüzde'), ('tutar', 'Sabit Tutar')], default='yuzde', max_length=10, verbose_name='Tür')),
                ('deger', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Değer')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('baslangic', models.DateField(blank=True, null=True, verbose_name='Başlangıç')),
                ('bitis', models.DateField(blank=True, null=True, verbose_name='Bitiş')),
                ('aciklama', models.CharField(blank=True, max_length=255, verbose_name='Açıklama')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'İndirim',
                'verbose_name_plural': 'İndirimler',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='FinansKampanya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=120, verbose_name='Kampanya adı')),
                ('baslangic', models.DateField(verbose_name='Başlangıç')),
                ('bitis', models.DateField(verbose_name='Bitiş')),
                ('kosullar', models.TextField(blank=True, verbose_name='Koşullar')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('indirim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kampanyalar', to='takip.finansindirim', verbose_name='İndirim')),
            ],
            options={
                'verbose_name': 'Kampanya',
                'verbose_name_plural': 'Kampanyalar',
                'ordering': ['-baslangic'],
            },
        ),
        migrations.CreateModel(
            name='TalebeFinansDosyasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toplam_ucret', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('indirim_tutari', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_ucret', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pesinat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('odenen_tutar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('taksit_sayisi', models.PositiveSmallIntegerField(default=10, verbose_name='Taksit sayısı')),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('devam', 'Devam Ediyor'), ('tamamlandi', 'Tamamlandı'), ('gecikti', 'Gecikti')], default='bekliyor', max_length=12)),
                ('not_alani', models.TextField(blank=True, verbose_name='Not')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('egitim_yili', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finans_dosyalari', to='takip.egitimyili', verbose_name='Eğitim yılı')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_finans_dosyalari', to=settings.AUTH_USER_MODEL)),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finans_dosyalari', to='takip.talebe', verbose_name='Talebe')),
            ],
            options={
                'verbose_name': 'Öğrenci finans dosyası',
                'verbose_name_plural': 'Öğrenci finans dosyaları',
                'ordering': ['-egitim_yili__baslangic', 'talebe__ad_soyad'],
            },
        ),
        migrations.CreateModel(
            name='FinansTaksit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira', models.PositiveSmallIntegerField(verbose_name='Sıra')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vade', models.DateField(verbose_name='Vade')),
                ('odenen_tutar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('odendi', 'Ödendi'), ('kismi', 'Kısmi'), ('gecikti', 'Gecikti')], default='bekliyor', max_length=10)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('dosya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taksitler', to='takip.talebefinansdosyasi', verbose_name='Finans dosyası')),
            ],
            options={
                'verbose_name': 'Taksit',
                'verbose_name_plural': 'Taksitler',
                'ordering': ['dosya', 'sira'],
            },
        ),
        migrations.CreateModel(
            name='FinansTahsilat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('yontem', models.CharField(choices=[('nakit', 'Nakit'), ('eft', 'EFT'), ('kart', 'Kart'), ('diger', 'Diğer')], default='nakit', max_length=10)),
                ('tur', models.CharField(choices=[('pesinat', 'Peşinat'), ('taksit', 'Taksit'), ('diger', 'Diğer')], default='taksit', max_length=10)),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('iptal', models.BooleanField(default=False, verbose_name='İptal')),
                ('iptal_nedeni', models.TextField(blank=True, verbose_name='İptal nedeni')),
                ('iptal_tarihi', models.DateTimeField(blank=True, null=True)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('iptal_eden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iptal_ettigi_finans_tahsilatlari', to=settings.AUTH_USER_MODEL)),
                ('kaydeden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaydettigi_finans_tahsilatlari', to=settings.AUTH_USER_MODEL)),
                ('taksit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tahsilatlar', to='takip.finanstaksit', verbose_name='Taksit')),
                ('dosya', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tahsilatlar', to='takip.talebefinansdosyasi', verbose_name='Finans dosyası')),
            ],
            options={
                'verbose_name': 'Finans tahsilat',
                'verbose_name_plural': 'Finans tahsilatları',
                'ordering': ['-tarih', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinansIslemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem', models.CharField(max_length=80, verbose_name='İşlem')),
                ('detay', models.TextField(blank=True, verbose_name='Detay')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finans_islem_loglari', to=settings.AUTH_USER_MODEL)),
                ('talebe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finans_islem_loglari', to='takip.talebe')),
                ('dosya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='islem_loglari', to='takip.talebefinansdosyasi')),
            ],
            options={
                'verbose_name': 'Finans işlem logu',
                'verbose_name_plural': 'Finans işlem logları',
                'ordering': ['-olusturulma'],
            },
        ),
        migrations.CreateModel(
            name='FinansUcretPolitikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinif_seviyesi', models.CharField(choices=[('5', '5. Sınıf'), ('6', '6. Sınıf'), ('7', '7. Sınıf'), ('8', '8. Sınıf')], max_length=2, verbose_name='Sınıf')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Yıllık ücret')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('egitim_yili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finans_ucret_politikalari', to='takip.egitimyili', verbose_name='Eğitim yılı')),
            ],
            options={
                'verbose_name': 'Ücret politikası',
                'verbose_name_plural': 'Ücret politikaları',
                'ordering': ['egitim_yili__baslangic', 'sinif_seviyesi'],
                'constraints': [models.UniqueConstraint(fields=('egitim_yili', 'sinif_seviyesi'), name='benzersiz_finans_ucret_politikasi')],
            },
        ),
        migrations.AddConstraint(
            model_name='talebefinansdosyasi',
            constraint=models.UniqueConstraint(fields=('talebe', 'egitim_yili'), name='benzersiz_talebe_finans_yil'),
        ),
        migrations.AddConstraint(
            model_name='finanstaksit',
            constraint=models.UniqueConstraint(fields=('dosya', 'sira'), name='benzersiz_finans_taksit_sira'),
        ),
    ]
