# Generated by Django 6.1 on 2026-08-07 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0037_finans_modulu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mezunprofil',
            name='bolum',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bölüm'),
        ),
        migrations.AddField(
            model_name='mezunprofil',
            name='calistigi_kurum',
            field=models.CharField(blank=True, max_length=200, verbose_name='Çalıştığı kurum'),
        ),
        migrations.AddField(
            model_name='mezunprofil',
            name='iletisim_durumu',
            field=models.CharField(choices=[('iletisimde', 'İletişimde'), ('duzenli', 'Düzenli İletişim'), ('pasif', 'Pasif'), ('gorusulmedi', 'Görüşülmedi')], default='iletisimde', max_length=16, verbose_name='İletişim durumu'),
        ),
        migrations.AddField(
            model_name='mezunprofil',
            name='kurum_bagi',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('duzenli_iletisim', 'Düzenli İletişim'), ('etkinlik_katilimci', 'Etkinlik Katılımcısı'), ('uzun_sure', 'Uzun Süredir Görüşülmedi')], default='aktif', max_length=20, verbose_name='Kurum bağı'),
        ),
        migrations.AddField(
            model_name='mezunprofil',
            name='lgs_yuzdelik',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='LGS yüzdelik dilim'),
        ),
        migrations.AddField(
            model_name='mezunprofil',
            name='lise_yerlesme_yili',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Lise yerleşme yılı'),
        ),
        migrations.AddField(
            model_name='mezunprofil',
            name='meslek',
            field=models.CharField(blank=True, max_length=120, verbose_name='Meslek'),
        ),
        migrations.AddField(
            model_name='mezunprofil',
            name='sehir',
            field=models.CharField(blank=True, max_length=80, verbose_name='Şehir'),
        ),
        migrations.AddField(
            model_name='mezunprofil',
            name='son_gorusme_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Son görüşme'),
        ),
        migrations.AddField(
            model_name='mezunprofil',
            name='ulke',
            field=models.CharField(blank=True, default='Türkiye', max_length=80, verbose_name='Ülke'),
        ),
        migrations.AddField(
            model_name='mezunprofil',
            name='universite',
            field=models.CharField(blank=True, max_length=200, verbose_name='Üniversite'),
        ),
        migrations.AddField(
            model_name='mezunprofil',
            name='universite_yerlesme_yili',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Üniversite yerleşme yılı'),
        ),
        migrations.AddField(
            model_name='mezunprofil',
            name='yks_sira',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='YKS başarı sırası'),
        ),
        migrations.AlterField(
            model_name='mezunprofil',
            name='iletisim_adres',
            field=models.TextField(blank=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='mezunprofil',
            name='iletisim_eposta',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='mezunprofil',
            name='iletisim_telefon',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon'),
        ),
        migrations.CreateModel(
            name='MezunBasari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('kategori', models.CharField(choices=[('lgs', 'LGS Başarısı'), ('yks', 'YKS Başarısı'), ('akademik', 'Akademik Başarı'), ('mesleki', 'Mesleki Başarı'), ('spor', 'Spor'), ('sanat', 'Sanat'), ('odul', 'Ödül'), ('proje', 'Proje'), ('diger', 'Diğer')], default='diger', max_length=16)),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('kurum_yarisma', models.CharField(blank=True, max_length=200, verbose_name='Kurum / Yarışma')),
                ('arsivde_goster', models.BooleanField(default=False, verbose_name='Başarı arşivinde göster')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('kaydeden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaydettigi_mezun_basarilari', to=settings.AUTH_USER_MODEL)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basarilar', to='takip.mezunprofil', verbose_name='Mezun profili')),
            ],
            options={
                'verbose_name': 'Mezun başarısı',
                'verbose_name_plural': 'Mezun başarıları',
                'ordering': ['-tarih', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MezunEtkinlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Etkinlik adı')),
                ('tur', models.CharField(choices=[('bulusma', 'Mezun Buluşması'), ('seminer', 'Seminer'), ('kariyer', 'Kariyer Günü'), ('soylesi', 'Söyleşi'), ('tanitim', 'Tanıtım Günü'), ('ziyaret', 'Kurum Ziyareti')], default='bulusma', max_length=16)),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('saat', models.TimeField(blank=True, null=True, verbose_name='Saat')),
                ('yer', models.CharField(blank=True, max_length=200, verbose_name='Yer')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_mezun_etkinlikleri', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mezun etkinliği',
                'verbose_name_plural': 'Mezun etkinlikleri',
                'ordering': ['-tarih', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MezunGuncellemeGorevi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Görev başlığı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('son_tarih', models.DateField(verbose_name='Son tarih')),
                ('talep_edilen_alanlar', models.JSONField(blank=True, default=list, verbose_name='Talep edilen alanlar')),
                ('mezuniyet_yili', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mezuniyet yılı filtresi')),
                ('tamamlandi', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_mezun_gorevleri', to=settings.AUTH_USER_MODEL)),
                ('sorumlu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mezun_guncelleme_gorevleri', to=settings.AUTH_USER_MODEL, verbose_name='Sorumlu personel')),
            ],
            options={
                'verbose_name': 'Mezun güncelleme görevi',
                'verbose_name_plural': 'Mezun güncelleme görevleri',
                'ordering': ['-olusturulma'],
            },
        ),
        migrations.CreateModel(
            name='MezunIletisim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('telefon', 'Telefon'), ('whatsapp', 'WhatsApp'), ('ziyaret', 'Ziyaret'), ('seminer', 'Seminer'), ('bulusma', 'Mezun Buluşması'), ('kariyer', 'Kariyer Görüşmesi'), ('diger', 'Diğer')], default='telefon', max_length=16)),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('kaydeden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mezun_iletisim_kayitlari', to=settings.AUTH_USER_MODEL)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iletisim_kayitlari', to='takip.mezunprofil', verbose_name='Mezun profili')),
            ],
            options={
                'verbose_name': 'Mezun iletişim kaydı',
                'verbose_name_plural': 'Mezun iletişim kayıtları',
                'ordering': ['-tarih', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MezunYolculukOlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.PositiveSmallIntegerField(verbose_name='Yıl')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('tur', models.CharField(choices=[('mezuniyet', 'Mezuniyet'), ('lgs', 'LGS'), ('lise', 'Lise'), ('etkinlik', 'Etkinlik'), ('yks', 'YKS'), ('universite', 'Üniversite'), ('kariyer', 'Kariyer'), ('diger', 'Diğer')], default='diger', max_length=16)),
                ('tarih', models.DateField(blank=True, null=True, verbose_name='Tarih')),
                ('otomatik', models.BooleanField(default=False, verbose_name='Otomatik')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yolculuk_olaylari', to='takip.mezunprofil', verbose_name='Mezun profili')),
            ],
            options={
                'verbose_name': 'Mezun yolculuk olayı',
                'verbose_name_plural': 'Mezun yolculuk olayları',
                'ordering': ['-yil', '-tarih', '-sira', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MezunEtkinlikKatilim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('katildi', 'Katıldı'), ('katilmadi', 'Katılmadı'), ('davet', 'Davet Edildi'), ('beklemede', 'Cevap Bekleniyor')], default='davet', max_length=12)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('etkinlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='katilimlar', to='takip.mezunetkinlik', verbose_name='Etkinlik')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etkinlik_katilimlari', to='takip.mezunprofil', verbose_name='Mezun')),
            ],
            options={
                'verbose_name': 'Etkinlik katılımı',
                'verbose_name_plural': 'Etkinlik katılımları',
                'constraints': [models.UniqueConstraint(fields=('etkinlik', 'profil'), name='benzersiz_mezun_etkinlik_katilim')],
            },
        ),
        migrations.CreateModel(
            name='MezunGuncellemeGorevKayit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamamlandi', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('gorev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kayitlar', to='takip.mezunguncellemegorevi', verbose_name='Görev')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guncelleme_gorevleri', to='takip.mezunprofil', verbose_name='Mezun')),
            ],
            options={
                'verbose_name': 'Görev kaydı',
                'verbose_name_plural': 'Görev kayıtları',
                'constraints': [models.UniqueConstraint(fields=('gorev', 'profil'), name='benzersiz_mezun_gorev_kayit')],
            },
        ),
    ]
