# Generated by Django 6.1 on 2026-08-07 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0038_mezun_takip_merkezi'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandevuMusaitlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hafta_gunu', models.PositiveSmallIntegerField(choices=[(0, 'Pazartesi'), (1, 'Salı'), (2, 'Çarşamba'), (3, 'Perşembe'), (4, 'Cuma'), (5, 'Cumartesi'), (6, 'Pazar')], verbose_name='Gün')),
                ('baslangic', models.TimeField(verbose_name='Başlangıç')),
                ('bitis', models.TimeField(verbose_name='Bitiş')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='randevu_musaitlikleri', to='takip.personelprofili', verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Randevu müsaitliği',
                'verbose_name_plural': 'Randevu müsaitlikleri',
                'ordering': ['hafta_gunu', 'baslangic'],
            },
        ),
        migrations.CreateModel(
            name='RandevuPersonelAyar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktif', models.BooleanField(default=False, verbose_name='Randevu alabilir')),
                ('sure_dk', models.PositiveSmallIntegerField(default=30, verbose_name='Görüşme süresi (dk)')),
                ('aciklama', models.CharField(blank=True, max_length=255, verbose_name='Veliye gösterilen açıklama')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('personel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='randevu_ayari', to='takip.personelprofili', verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Randevu personel ayarı',
                'verbose_name_plural': 'Randevu personel ayarları',
            },
        ),
        migrations.CreateModel(
            name='VeliRandevu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('baslangic', models.TimeField(verbose_name='Başlangıç')),
                ('bitis', models.TimeField(verbose_name='Bitiş')),
                ('konu', models.CharField(blank=True, max_length=255, verbose_name='Konu')),
                ('durum', models.CharField(choices=[('planlandi', 'Planlandı'), ('tamamlandi', 'Tamamlandı'), ('iptal_veli', 'Veli İptal'), ('iptal_personel', 'Personel İptal')], default='planlandi', max_length=20)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('gorusme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='veli_randevulari', to='takip.ogrencigorusmesi', verbose_name='Görüşme kaydı')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veli_randevulari', to='takip.personelprofili', verbose_name='Personel')),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veli_randevulari', to='takip.talebe', verbose_name='Talebe')),
                ('veli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='randevulari', to='takip.velihesap', verbose_name='Veli')),
            ],
            options={
                'verbose_name': 'Veli randevusu',
                'verbose_name_plural': 'Veli randevuları',
                'ordering': ['tarih', 'baslangic'],
                'constraints': [models.UniqueConstraint(fields=('personel', 'tarih', 'baslangic'), name='benzersiz_personel_randevu_slot')],
            },
        ),
    ]
