# Generated by Django 6.1 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takip", "0039_veli_randevu_sistemi"),
    ]

    operations = [
        migrations.AddField(
            model_name="etutgrupsaatbloku",
            name="durum",
            field=models.CharField(
                choices=[
                    ("aktif", "Aktif"),
                    ("pasif", "Pasif"),
                    ("izinli", "İzinli"),
                ],
                default="aktif",
                max_length=8,
                verbose_name="Durum",
            ),
        ),
    ]
