# Generated by Django 6.1 on 2026-08-07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takip", "0040_etut_saat_durum"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="temizlikgorevlisi",
            name="guncellenme",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="TemizlikGunlukKontrol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarih", models.DateField(verbose_name="Tarih")),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("bekliyor", "Bekliyor"),
                            ("tamamlandi", "Tamamlandı"),
                            ("eksik", "Eksik"),
                            ("kontrol", "Kontrol Edildi"),
                        ],
                        default="bekliyor",
                        max_length=12,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "notu",
                    models.CharField(blank=True, max_length=255, verbose_name="Not"),
                ),
                ("guncellenme", models.DateTimeField(auto_now=True)),
                (
                    "alan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gunluk_kontroller",
                        to="takip.temizlikalani",
                        verbose_name="Mahal",
                    ),
                ),
                (
                    "guncelleyen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="temizlik_kontrolleri",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Güncelleyen",
                    ),
                ),
                (
                    "liste",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gunluk_kontroller",
                        to="takip.temizliklistesi",
                        verbose_name="Liste",
                    ),
                ),
            ],
            options={
                "verbose_name": "Temizlik günlük kontrol",
                "verbose_name_plural": "Temizlik günlük kontroller",
            },
        ),
        migrations.AddConstraint(
            model_name="temizlikgunlukkontrol",
            constraint=models.UniqueConstraint(
                fields=("liste", "alan", "tarih"),
                name="benzersiz_temizlik_gun_kontrol",
            ),
        ),
    ]
