# Generated by Django 6.1 on 2026-08-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0041_temizlik_yonetim_merkezi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personelprofili',
            name='ana_rol',
            field=models.CharField(choices=[('idareci', 'İdareci'), ('ic_mesul', 'İç Mesul'), ('egitim_mesul', 'Eğitim Mesulü'), ('etut_mesul', 'Etüt Mesulü'), ('sinif_mesul', 'Sınıf Mesulü'), ('rehber_ogretmeni', 'Rehber Öğretmeni'), ('muhasebeci', 'Muhasebeci'), ('nehari_mesul', 'Nehari Mesulü'), ('mahal_sorumlusu', 'Mahal Sorumlusu')], default='etut_mesul', max_length=30, verbose_name='Ana rol'),
        ),
    ]
