# Generated by Django 6.1 on 2026-08-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0043_talebe_tc_kimlik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duyuru',
            name='hedef_kitle',
            field=models.CharField(choices=[('tum_personel', 'Tüm personel'), ('personel', 'Personel paneli'), ('ogretmen', 'Öğretmen paneli'), ('veli', 'Veli paneli')], default='tum_personel', max_length=20, verbose_name='Hedef kitle'),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='ozet',
            field=models.TextField(max_length=4000, verbose_name='Kısa açıklama'),
        ),
    ]
