# Generated by Django 6.1 on 2026-08-08 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0060_talebe_genis_profil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CumaDurumMetni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metin', models.TextField(verbose_name='Hadis / söz')),
                ('kaynak', models.CharField(blank=True, help_text='Örn. Buhari, Müslim, Mevlana', max_length=200, verbose_name='Kaynak')),
                ('sablon', models.CharField(choices=[('gece', 'Gece mavisi'), ('zumrut', 'Zümrüt yeşili'), ('mor', 'Mor ışık'), ('altin', 'Altın şafak'), ('lacivert', 'Lacivert')], default='gece', max_length=16, verbose_name='Görsel tema')),
                ('cuma_tarihi', models.DateField(blank=True, help_text='Belirli bir Cuma günü için sabit metin. Boş bırakılırsa otomatik sıradan seçilir.', null=True, verbose_name='Atanan Cuma')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuma durum metni',
                'verbose_name_plural': 'Cuma durum metinleri',
                'ordering': ['sira', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='panelkisayolgorsel',
            options={'ordering': ['anahtar'], 'verbose_name': 'Panel kısayol görseli (eski)', 'verbose_name_plural': 'Panel kısayol görselleri (eski)'},
        ),
        migrations.RenameIndex(
            model_name='bildirim',
            new_name='takip_bildi_alici_i_7022a3_idx',
            old_name='takip_bildi_alici_i_7c8a1d_idx',
        ),
        migrations.RenameIndex(
            model_name='bildirim',
            new_name='takip_bildi_alici_i_917e7a_idx',
            old_name='takip_bildi_alici_i_2f9b0e_idx',
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='hedef_kitle',
            field=models.CharField(choices=[('tum_personel', 'Herkese (Personel + Öğretmen + Veli)'), ('personel', 'Yalnızca personel paneli'), ('ogretmen', 'Yalnızca öğretmen paneli'), ('veli', 'Yalnızca veli paneli')], default='tum_personel', max_length=20, verbose_name='Hedef kitle'),
        ),
        migrations.AlterField(
            model_name='panelkisayolgorsel',
            name='aktif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='panelkisayolgorsel',
            name='anahtar',
            field=models.SlugField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='panelkisayolgorsel',
            name='baslik',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='panelkisayolgorsel',
            name='gorsel',
            field=models.ImageField(blank=True, null=True, upload_to='panel_kisayol/'),
        ),
        migrations.AlterField(
            model_name='personelvazife',
            name='bitis',
            field=models.DateField(blank=True, null=True, verbose_name='Şu güne kadar'),
        ),
        migrations.AddField(
            model_name='cumadurummetni',
            name='olusturan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_cuma_durum_metinleri', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan'),
        ),
    ]
