# Generated by Django 6.1 on 2026-08-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0065_dini_ders_seviyeleri_varsayilan'),
    ]

    operations = [
        migrations.AddField(
            model_name='kttsinav',
            name='haric_talebeler',
            field=models.ManyToManyField(blank=True, help_text='Sınava katılmayan ve sonuç listesinden çıkarılan öğrenciler.', related_name='ktt_haric', to='takip.talebe', verbose_name='Katılmayan / hariç talebeler'),
        ),
        migrations.AlterField(
            model_name='pazarizindonuskaydi',
            name='durum',
            field=models.CharField(choices=[('geldi', 'GELDİ'), ('izinli', 'İZİNLİ'), ('gec_geldi', 'GEÇ GELDİ'), ('gelmedi', 'GELMEDİ')], default='gelmedi', max_length=12, verbose_name='Durum'),
        ),
    ]
