# Generated by Django 6.1 on 2026-08-09 23:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0067_talebe_biyometrik_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiuretimkaydi',
            name='tur',
            field=models.CharField(choices=[('gelisim_zekasi', 'Gelişim Zekası'), ('mudahale_oneri', 'Müdahale Önerisi'), ('veli_haftalik', 'Veli Haftalık Özet'), ('deneme_analiz', 'Deneme Analizi'), ('rehberlik_ozet', 'Rehberlik Özeti'), ('kurum_zekasi', 'Kurum Zekası'), ('soru_takip', 'Soru Takip İçgörüsü'), ('veli_takip', 'Veli Takip Raporu')], max_length=32, verbose_name='Tür'),
        ),
        migrations.CreateModel(
            name='KonuKatalogu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinif_seviyesi', models.CharField(help_text='Örn. 5, 6, 7, 8', max_length=30, verbose_name='Sınıf seviyesi')),
                ('brans', models.CharField(choices=[('turkce', 'Türkçe'), ('matematik', 'Matematik'), ('fen', 'Fen Bilimleri'), ('sosyal', 'Sosyal Bilgiler'), ('din', 'Din Kültürü'), ('ingilizce', 'İngilizce')], max_length=20, verbose_name='Branş')),
                ('konu_ad', models.CharField(max_length=200, verbose_name='Konu adı')),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Konu kataloğu',
                'verbose_name_plural': 'Konu kataloğu',
                'ordering': ['sinif_seviyesi', 'brans', 'konu_ad'],
                'constraints': [models.UniqueConstraint(fields=('sinif_seviyesi', 'brans', 'konu_ad'), name='konu_katalog_benzersiz')],
            },
        ),
        migrations.CreateModel(
            name='KonuEgitimVideosu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=300, verbose_name='Video başlığı')),
                ('youtube_id', models.CharField(blank=True, help_text='Boş bırakılırsa arama sorgusu kullanılır.', max_length=20, verbose_name='YouTube video ID')),
                ('arama_sorgusu', models.CharField(blank=True, help_text='Video ID yoksa panel içi arama oynatıcısı için kullanılır.', max_length=300, verbose_name='YouTube arama sorgusu')),
                ('tur', models.CharField(choices=[('anlatim', 'Konu anlatımı'), ('cozum', 'Soru çözümü'), ('tekrar', 'Kısa tekrar')], default='anlatim', max_length=20, verbose_name='Tür')),
                ('sira', models.PositiveSmallIntegerField(default=1, verbose_name='Sıra (1-3)')),
                ('sure_dk', models.PositiveSmallIntegerField(default=10, verbose_name='Süre (dk)')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('konu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videolar', to='takip.konukatalogu', verbose_name='Konu')),
            ],
            options={
                'verbose_name': 'Eğitim videosu',
                'verbose_name_plural': 'Eğitim videoları',
                'ordering': ['konu_id', 'sira', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KonuSorusu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru_metni', models.TextField(verbose_name='Soru metni')),
                ('secenek_a', models.CharField(max_length=500, verbose_name='A şıkkı')),
                ('secenek_b', models.CharField(max_length=500, verbose_name='B şıkkı')),
                ('secenek_c', models.CharField(max_length=500, verbose_name='C şıkkı')),
                ('secenek_d', models.CharField(max_length=500, verbose_name='D şıkkı')),
                ('dogru_secenek', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Doğru cevap')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('sira', models.PositiveSmallIntegerField(default=1, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('konu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorular', to='takip.konukatalogu', verbose_name='Konu')),
            ],
            options={
                'verbose_name': 'Konu sorusu',
                'verbose_name_plural': 'Konu soruları',
                'ordering': ['konu_id', 'sira', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KonuTestOturu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslama', models.DateTimeField(auto_now_add=True)),
                ('bitis', models.DateTimeField(blank=True, null=True)),
                ('dogru_sayisi', models.PositiveSmallIntegerField(default=0)),
                ('toplam_soru', models.PositiveSmallIntegerField(default=0)),
                ('basari_yuzde', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('konu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_oturumlari', to='takip.konukatalogu', verbose_name='Konu')),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konu_test_oturumlari', to='takip.talebe', verbose_name='Talebe')),
            ],
            options={
                'verbose_name': 'Konu test oturumu',
                'verbose_name_plural': 'Konu test oturumları',
                'ordering': ['-baslama', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KonuTestCevabi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secilen', models.CharField(max_length=1, verbose_name='Seçilen şık')),
                ('dogru_mu', models.BooleanField(default=False)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cevaplar', to='takip.konusorusu', verbose_name='Soru')),
                ('oturum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cevaplar', to='takip.konutestoturu', verbose_name='Oturum')),
            ],
            options={
                'verbose_name': 'Konu test cevabı',
                'verbose_name_plural': 'Konu test cevapları',
            },
        ),
        migrations.CreateModel(
            name='KonuVideoIzleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_baslik', models.CharField(max_length=300, verbose_name='Video başlığı')),
                ('baslama', models.DateTimeField(verbose_name='Başlangıç')),
                ('bitis', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş')),
                ('sure_sn', models.PositiveIntegerField(default=0, verbose_name='İzleme süresi (sn)')),
                ('tamamlandi', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('konu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_izlemeleri', to='takip.konukatalogu', verbose_name='Konu')),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konu_video_izlemeleri', to='takip.talebe', verbose_name='Talebe')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='izlemeler', to='takip.konuegitimvideosu', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Video izleme kaydı',
                'verbose_name_plural': 'Video izleme kayıtları',
                'ordering': ['-baslama', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TalebeKonuEksigi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaynak', models.CharField(choices=[('ktt', 'KTT'), ('deneme', 'Deneme'), ('excel', 'Excel analiz'), ('ai', 'Yapay zeka'), ('manuel', 'Manuel')], max_length=20, verbose_name='Kaynak')),
                ('skor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Skor / puan')),
                ('oncelik', models.PositiveSmallIntegerField(default=50, verbose_name='Öncelik')),
                ('tespit_tarihi', models.DateField(verbose_name='Tespit tarihi')),
                ('cozuldu', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('notlar', models.TextField(blank=True, verbose_name='Not')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('konu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talebe_eksikleri', to='takip.konukatalogu', verbose_name='Konu')),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konu_eksikleri', to='takip.talebe', verbose_name='Talebe')),
            ],
            options={
                'verbose_name': 'Talebe konu eksiği',
                'verbose_name_plural': 'Talebe konu eksikleri',
                'ordering': ['-oncelik', '-tespit_tarihi', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='konuegitimvideosu',
            constraint=models.UniqueConstraint(fields=('konu', 'sira'), name='konu_video_sira_benzersiz'),
        ),
        migrations.AddConstraint(
            model_name='konutestcevabi',
            constraint=models.UniqueConstraint(fields=('oturum', 'soru'), name='konu_test_soru_tek_cevap'),
        ),
        migrations.AddConstraint(
            model_name='talebekonueksigi',
            constraint=models.UniqueConstraint(fields=('talebe', 'konu', 'kaynak'), name='talebe_konu_kaynak_benzersiz'),
        ),
    ]
