# Generated by Django 6.1 on 2026-08-10 09:33

import django.db.models.deletion
import takip.sinav_basvuru_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0071_sinav_basvuru_durum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinavbasvuru',
            name='durum',
            field=models.ForeignKey(default=takip.sinav_basvuru_models.varsayilan_basvuru_durumu, on_delete=django.db.models.deletion.PROTECT, related_name='basvurular', to='takip.sinavbasvurudurum', verbose_name='Durum'),
        ),
    ]
