# Generated by Django 6.1 on 2026-08-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0072_alter_sinavbasvuru_durum_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='talebe',
            name='ev_adresi',
            field=models.TextField(blank=True, verbose_name='Veli ev adresi'),
        ),
        migrations.AddField(
            model_name='talebe',
            name='memleket_ilce',
            field=models.CharField(blank=True, max_length=120, verbose_name='Memleket ilçesi'),
        ),
        migrations.AlterField(
            model_name='talebe',
            name='memleket',
            field=models.CharField(blank=True, max_length=120, verbose_name='Memleket ili'),
        ),
    ]
