# Generated by Django 6.1 on 2026-08-10 17:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0074_program_faaliyet_turu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DenemeGapRaporu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya_adi', models.CharField(max_length=255, verbose_name='Dosya adı')),
                ('ham_ad', models.CharField(blank=True, max_length=200, verbose_name='PDF’deki ad')),
                ('sinif_metni', models.CharField(blank=True, max_length=40, verbose_name='Sınıf (PDF)')),
                ('eslesme', models.CharField(choices=[('otomatik', 'Otomatik'), ('alias', 'Alias'), ('oneri', 'Öneri'), ('manuel', 'Manuel'), ('yok', 'Eşleşmedi')], default='yok', max_length=20, verbose_name='Eşleşme')),
                ('durum', models.CharField(choices=[('islendi', 'İşlendi'), ('eslesme_bekliyor', 'Eşleşme bekliyor'), ('hata', 'Hata')], default='eslesme_bekliyor', max_length=20, verbose_name='Durum')),
                ('hata_mesaji', models.TextField(blank=True, verbose_name='Hata')),
                ('ham_metin_ozet', models.TextField(blank=True, verbose_name='Ham metin özeti')),
                ('oneri_talebe_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Öneri talebe id')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('deneme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_raporlari', to='takip.denemesinavi', verbose_name='Deneme')),
                ('talebe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deneme_gap_raporlari', to='takip.talebe', verbose_name='Talebe')),
                ('yukleyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yukledigi_gap_raporlari', to=settings.AUTH_USER_MODEL, verbose_name='Yükleyen')),
            ],
            options={
                'verbose_name': 'Deneme gap raporu',
                'verbose_name_plural': 'Deneme gap raporları',
                'ordering': ['-olusturulma', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DenemeKonuSonucu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brans', models.CharField(choices=[('turkce', 'Türkçe'), ('matematik', 'Matematik'), ('fen', 'Fen Bilimleri'), ('sosyal', 'Sosyal Bilgiler'), ('din', 'Din Kültürü'), ('ingilizce', 'İngilizce')], max_length=20, verbose_name='Branş')),
                ('konu_ham', models.CharField(max_length=300, verbose_name='Konu (PDF)')),
                ('konu_normalize', models.CharField(blank=True, max_length=300, verbose_name='Konu (normalize)')),
                ('toplam', models.PositiveIntegerField(default=0)),
                ('dogru', models.PositiveIntegerField(default=0)),
                ('yanlis', models.PositiveIntegerField(default=0)),
                ('bos', models.PositiveIntegerField(default=0)),
                ('yuzde', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='Başarı %')),
                ('rapor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konu_satirlari', to='takip.denemegapraporu', verbose_name='Gap raporu')),
                ('sonuc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='konu_satirlari', to='takip.denemesonucu', verbose_name='Deneme sonucu')),
            ],
            options={
                'verbose_name': 'Deneme konu sonucu',
                'verbose_name_plural': 'Deneme konu sonuçları',
                'ordering': ['brans', 'yuzde', 'konu_normalize', 'id'],
                'indexes': [models.Index(fields=['sonuc', 'brans'], name='takip_denem_sonuc_i_6b0753_idx'), models.Index(fields=['rapor', 'yuzde'], name='takip_denem_rapor_i_89c96c_idx')],
            },
        ),
    ]
