# Generated by Django 6.1 on 2026-08-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0075_deneme_gap_raporu'),
    ]

    operations = [
        migrations.AddField(
            model_name='konusorusu',
            name='soru_turu',
            field=models.CharField(choices=[('temel', 'Temel'), ('kavrama', 'Kavrama'), ('uygulama', 'Uygulama'), ('yeni_nesil', 'Yeni nesil'), ('kisisel', 'Kişisel pekiştirme')], default='temel', max_length=20, verbose_name='Soru türü'),
        ),
    ]
