# Generated by Django 6.1 on 2026-08-13 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0077_dershane_demo_atama_temizle'),
    ]

    operations = [
        migrations.AddField(
            model_name='diniderskonukaydi',
            name='tamamlanma_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Tamamlanma tarihi'),
        ),
        migrations.CreateModel(
            name='DiniIlerlemeEsik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_onunde_puan', models.PositiveSmallIntegerField(default=8, verbose_name='Planın önünde (puan farkı)')),
                ('geride_puan', models.SmallIntegerField(default=-8, verbose_name='Planın gerisinde (puan farkı)')),
                ('grupla_uyumlu_puan', models.PositiveSmallIntegerField(default=5, verbose_name='Grupla uyumlu (± puan)')),
                ('hiz_artis_esik_puan', models.PositiveSmallIntegerField(default=5, verbose_name='Son dönem hız artışı (puan)')),
                ('egitim_yili', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dini_ilerleme_esikleri', to='takip.egitimyili', verbose_name='Eğitim yılı')),
            ],
            options={
                'verbose_name': 'Dini ilerleme eşiği',
                'verbose_name_plural': 'Dini ilerleme eşikleri',
            },
        ),
        migrations.CreateModel(
            name='DiniKonuHedefTarihi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hedef_tarih', models.DateField(verbose_name='Hedef tarih')),
                ('aciklama', models.CharField(blank=True, max_length=200, verbose_name='Açıklama')),
                ('konu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hedef_tarihi_kaydi', to='takip.diniderskonu', verbose_name='Konu')),
            ],
            options={
                'verbose_name': 'Dini konu hedef tarihi',
                'verbose_name_plural': 'Dini konu hedef tarihleri',
                'ordering': ['hedef_tarih'],
            },
        ),
        migrations.CreateModel(
            name='DiniAlanPlani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birinci_donem_hedef', models.PositiveSmallIntegerField(default=0, help_text='0 ise yıl içi doğrusal dağılım kullanılır.', verbose_name='1. dönem sonu hedef (konu adedi)')),
                ('yil_sonu_hedef', models.PositiveSmallIntegerField(default=0, help_text='0 ise tüm aktif konu sayısı hedef kabul edilir.', verbose_name='Yıl sonu hedef (konu adedi)')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('alan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seviye_planlari', to='takip.diniderstakipalani', verbose_name='Takip alanı')),
                ('egitim_yili', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dini_alan_planlari', to='takip.egitimyili', verbose_name='Eğitim yılı')),
                ('seviye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alan_planlari', to='takip.dinidersseviyesi', verbose_name='Seviye')),
            ],
            options={
                'verbose_name': 'Dini alan planı',
                'verbose_name_plural': 'Dini alan planları',
                'ordering': ['egitim_yili__baslangic', 'seviye__sira', 'alan__sira'],
                'constraints': [models.UniqueConstraint(fields=('egitim_yili', 'seviye', 'alan'), name='dini_alan_plani_benzersiz')],
            },
        ),
    ]
