# Generated by Django 6.1 on 2026-08-13 10:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0079_ktt_akilli_takip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZiyaretPlani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Plan adı')),
                ('tarih', models.DateField(verbose_name='Ziyaret tarihi')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('durum', models.CharField(choices=[('taslak', 'Taslak'), ('arac_toplaniyor', 'Araç Toplanıyor'), ('dagitim', 'Dağıtım Yapılıyor'), ('hazir', 'Hazır'), ('arsiv', 'Arşiv')], default='taslak', max_length=20, verbose_name='Durum')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_ziyaret_planlari', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Ziyaret planı',
                'verbose_name_plural': 'Ziyaret planları',
                'ordering': ['-tarih', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ZiyaretAraci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surucu_ad', models.CharField(max_length=120, verbose_name='Araç sahibi / sürücü')),
                ('kapasite', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Talebe kapasitesi')),
                ('notlar', models.CharField(blank=True, max_length=300, verbose_name='Not')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('ekleyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buldugu_ziyaret_araclari', to='takip.etuthocasi', verbose_name='Aracı bulan etüt hocası')),
                ('surucu_personel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ziyaret_araclari', to='takip.personelprofili', verbose_name='Personel kaydı (varsa)')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='araclar', to='takip.ziyaretplani', verbose_name='Ziyaret planı')),
            ],
            options={
                'verbose_name': 'Ziyaret aracı',
                'verbose_name_plural': 'Ziyaret araçları',
                'ordering': ['surucu_ad', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ZiyaretProgramAdimi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saat', models.TimeField(verbose_name='Saat')),
                ('aciklama', models.CharField(max_length=300, verbose_name='Açıklama')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_adimlari', to='takip.ziyaretplani', verbose_name='Ziyaret planı')),
            ],
            options={
                'verbose_name': 'Program adımı',
                'verbose_name_plural': 'Program adımları',
                'ordering': ['sira', 'saat', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ZiyaretAracAtama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('talebe', 'Talebe'), ('etut_hocasi', 'Etüt Hocası')], max_length=16, verbose_name='Tür')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('etut_hocasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ziyaret_arac_atamalari', to='takip.etuthocasi', verbose_name='Etüt hocası')),
                ('talebe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ziyaret_arac_atamalari', to='takip.talebe', verbose_name='Talebe')),
                ('arac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atamalar', to='takip.ziyaretaraci', verbose_name='Araç')),
            ],
            options={
                'verbose_name': 'Ziyaret araç ataması',
                'verbose_name_plural': 'Ziyaret araç atamaları',
                'ordering': ['sira', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('talebe__isnull', False)), fields=('arac', 'talebe'), name='ziyaret_arac_talebe_tek'), models.UniqueConstraint(condition=models.Q(('etut_hocasi__isnull', False)), fields=('arac', 'etut_hocasi'), name='ziyaret_arac_etut_tek')],
            },
        ),
        migrations.CreateModel(
            name='ZiyaretPlaniTalebe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktif', models.BooleanField(default=True, verbose_name='Listede aktif')),
                ('sabit', models.BooleanField(default=False, verbose_name='Sabitle')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_talebeleri', to='takip.ziyaretplani', verbose_name='Ziyaret planı')),
                ('sabit_arac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sabit_talebeler', to='takip.ziyaretaraci', verbose_name='Sabit araç')),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ziyaret_plan_kayitlari', to='takip.talebe', verbose_name='Talebe')),
            ],
            options={
                'verbose_name': 'Ziyaret planı talebesi',
                'verbose_name_plural': 'Ziyaret planı talebeleri',
                'ordering': ['talebe__ad_soyad'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'talebe'), name='ziyaret_plan_talebe_tek')],
            },
        ),
    ]
