# Generated by Django 6.1 on 2026-08-13 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0080_ziyaret_arac_planlama'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IletisimKurumAyar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varsayilan_hitap', models.CharField(default='Değerli Velimiz,', max_length=120, verbose_name='Varsayılan hitap')),
                ('varsayilan_kapanis', models.CharField(default='Saygılarımızla,', max_length=200, verbose_name='Varsayılan kapanış')),
                ('kurum_imza', models.CharField(blank=True, help_text='Mesaj sonunda görünür; boş bırakılırsa panel adı kullanılır.', max_length=200, verbose_name='Kurum imzası')),
                ('guncellenme', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'İletişim kurum ayarı',
                'verbose_name_plural': 'İletişim kurum ayarları',
            },
        ),
        migrations.CreateModel(
            name='IletisimPaketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=240, verbose_name='Başlık')),
                ('kaynak_modul', models.CharField(choices=[('ktt', 'KTT'), ('deneme', 'Deneme'), ('kitap', 'Kitap'), ('karne', 'Karne'), ('dini_egitim', 'Dinî Eğitim'), ('program', 'Program'), ('yazili', 'Yazılı'), ('duyuru', 'Duyuru'), ('manuel', 'Manuel')], default='manuel', max_length=30, verbose_name='Kaynak modül')),
                ('kaynak_tur', models.CharField(blank=True, max_length=60, verbose_name='Kaynak tür')),
                ('kaynak_id', models.CharField(blank=True, max_length=64, verbose_name='Kaynak ID')),
                ('kaynak_imza', models.CharField(blank=True, help_text='Kaynak güncellendiğinde paket yenilenmesi için.', max_length=64, verbose_name='Kaynak imza')),
                ('hedef_tur', models.CharField(choices=[('sinif_velileri', 'Sınıf Velileri'), ('bireysel_veli', 'Bireysel Veli'), ('tum_veliler', 'Tüm Veliler'), ('ozel', 'Özel')], default='sinif_velileri', max_length=30, verbose_name='Hedef tür')),
                ('hedef_etiket', models.CharField(max_length=200, verbose_name='Hedef etiket')),
                ('mesaj', models.TextField(verbose_name='Mesaj metni')),
                ('kanal', models.CharField(choices=[('whatsapp', 'WhatsApp')], default='whatsapp', max_length=20, verbose_name='Kanal')),
                ('durum', models.CharField(choices=[('taslak', 'Taslak'), ('hazir', 'Paylaşmaya Hazır'), ('paylasim_baslatildi', 'Paylaşım Başlatıldı')], default='hazir', max_length=24, verbose_name='Durum')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_iletisim_paketleri', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('sinif_sube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iletisim_paketleri', to='takip.sinifsube', verbose_name='Sınıf / şube')),
                ('talebe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iletisim_paketleri', to='takip.talebe', verbose_name='Talebe')),
            ],
            options={
                'verbose_name': 'İletişim paketi',
                'verbose_name_plural': 'İletişim paketleri',
                'ordering': ['-guncellenme', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IletisimEki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='iletisim/ekler/%Y/%m/', verbose_name='Dosya')),
                ('dosya_adi', models.CharField(max_length=240, verbose_name='Dosya adı')),
                ('mime_type', models.CharField(default='application/pdf', max_length=80)),
                ('kaynak', models.CharField(choices=[('uretilen_pdf', 'Üretilen PDF'), ('mevcut_dosya', 'Mevcut dosya')], default='uretilen_pdf', max_length=20)),
                ('kaynak_modul', models.CharField(blank=True, max_length=30)),
                ('kaynak_id', models.CharField(blank=True, max_length=64)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('talebe', models.ForeignKey(blank=True, help_text='Bireysel belgelerde doğrulama için.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iletisim_ekleri', to='takip.talebe', verbose_name='İlişkili talebe')),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ekler', to='takip.iletisimpaketi', verbose_name='Paket')),
            ],
            options={
                'verbose_name': 'İletişim eki',
                'verbose_name_plural': 'İletişim ekleri',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IletisimSablon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.SlugField(max_length=80, unique=True, verbose_name='Kod')),
                ('ad', models.CharField(max_length=160, verbose_name='Şablon adı')),
                ('kategori', models.CharField(choices=[('akademik', 'Akademik'), ('kitap', 'Kitap'), ('dini', 'Dinî Eğitim'), ('program', 'Program'), ('etkinlik', 'Etkinlik'), ('idari', 'İdari')], default='akademik', max_length=20, verbose_name='Kategori')),
                ('kaynak_moduller', models.JSONField(blank=True, default=list, help_text='Örn. ["ktt", "deneme"] — boş ise tüm modüllerde.', verbose_name='Kaynak modüller')),
                ('icerik', models.TextField(verbose_name='Mesaj şablonu')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('varsayilan', models.BooleanField(default=False, verbose_name='Varsayılan')),
                ('sira', models.PositiveSmallIntegerField(default=50, verbose_name='Sıra')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_iletisim_sablonlari', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'İletişim şablonu',
                'verbose_name_plural': 'İletişim şablonları',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.AddField(
            model_name='iletisimpaketi',
            name='sablon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paketler', to='takip.iletisimsablon', verbose_name='Şablon'),
        ),
        migrations.CreateModel(
            name='IletisimOlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olay_tur', models.CharField(choices=[('package_created', 'Paket oluşturuldu'), ('pdf_generated', 'PDF oluşturuldu'), ('message_copied', 'Mesaj kopyalandı'), ('file_downloaded', 'Dosya indirildi'), ('whatsapp_share_opened', 'WhatsApp paylaşımı açıldı'), ('native_share_opened', 'Cihaz paylaşımı açıldı'), ('draft_saved', 'Taslak kaydedildi')], max_length=40)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iletisim_olaylari', to=settings.AUTH_USER_MODEL)),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olaylar', to='takip.iletisimpaketi', verbose_name='Paket')),
            ],
            options={
                'verbose_name': 'İletişim olayı',
                'verbose_name_plural': 'İletişim olayları',
                'ordering': ['-olusturulma'],
                'indexes': [models.Index(fields=['olay_tur', '-olusturulma'], name='takip_ileti_olay_tu_8d5c74_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='iletisimpaketi',
            index=models.Index(fields=['durum', '-guncellenme'], name='takip_ileti_durum_a377df_idx'),
        ),
        migrations.AddIndex(
            model_name='iletisimpaketi',
            index=models.Index(fields=['kaynak_modul', 'kaynak_tur', 'kaynak_id'], name='takip_ileti_kaynak__2eb1b0_idx'),
        ),
        migrations.AddIndex(
            model_name='iletisimpaketi',
            index=models.Index(fields=['talebe', '-guncellenme'], name='takip_ileti_talebe__be6bd1_idx'),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: __import__(
                "takip.iletisim_service", fromlist=["varsayilan_sablonlari_yukle"]
            ).varsayilan_sablonlari_yukle(),
            migrations.RunPython.noop,
        ),
    ]
