# Generated by Django 6.1 on 2026-08-13 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0081_iletisim_merkezi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kttsinav',
            name='deneme_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Deneme no'),
        ),
        migrations.AddField(
            model_name='kttsinav',
            name='deneme_serisi',
            field=models.CharField(blank=True, max_length=120, verbose_name='Deneme serisi'),
        ),
        migrations.AddField(
            model_name='kttsinav',
            name='durum',
            field=models.CharField(choices=[('taslak', 'Taslak'), ('zimmetleme_bekliyor', 'Zimmetleme bekliyor'), ('hazir', 'Hazır'), ('uygulandi', 'Uygulandı'), ('okuma_devam', 'Okuma devam ediyor'), ('sonuc_kontrol', 'Sonuçlar kontrol ediliyor'), ('sonuclandi', 'Sonuçlandı'), ('yayinlandi', 'Yayınlandı'), ('arsiv', 'Arşivlendi')], default='taslak', max_length=24, verbose_name='Durum'),
        ),
        migrations.AddField(
            model_name='kttsinav',
            name='kazanim_zorunlu',
            field=models.BooleanField(default=False, verbose_name='Kazanım zorunlu'),
        ),
        migrations.AddField(
            model_name='kttsinav',
            name='kitapcik_turleri',
            field=models.CharField(default='A', help_text='Virgülle: A,B,C,D', max_length=20, verbose_name='Kitapçık türleri'),
        ),
        migrations.AddField(
            model_name='kttsinav',
            name='secenek_sayisi',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Seçenek sayısı'),
        ),
        migrations.AddField(
            model_name='kttsinav',
            name='sinav_kodu',
            field=models.CharField(blank=True, max_length=40, verbose_name='Sınav kodu'),
        ),
        migrations.AddField(
            model_name='kttsinav',
            name='sinav_turu',
            field=models.CharField(choices=[('ktt', 'KTT — Konu Tarama Testi'), ('brans', 'Branş Denemesi'), ('sozel_sayisal', 'Sözel–Sayısal Deneme')], default='ktt', max_length=20, verbose_name='Sınav türü'),
        ),
        migrations.AddField(
            model_name='kttsinav',
            name='uygulama_saati',
            field=models.TimeField(blank=True, null=True, verbose_name='Uygulama saati'),
        ),
        migrations.AddField(
            model_name='kttsinav',
            name='yanlis_goturme_orani',
            field=models.PositiveSmallIntegerField(default=4, help_text='0 = kapalı; 4 = 3 yanlış 1 doğruyu götürür.', verbose_name='Yanlış götürme oranı'),
        ),
        migrations.AddField(
            model_name='kttsinav',
            name='yayinevi',
            field=models.CharField(blank=True, max_length=120, verbose_name='Yayınevi'),
        ),
        migrations.CreateModel(
            name='OlcumKazanim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kazanim_ad', models.CharField(max_length=300, verbose_name='Kazanım')),
                ('kod', models.CharField(blank=True, max_length=40, verbose_name='Kod')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('konu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kazanimlar', to='takip.konukatalogu', verbose_name='Konu')),
            ],
            options={
                'verbose_name': 'Kazanım',
                'verbose_name_plural': 'Kazanımlar',
                'ordering': ['konu_id', 'kazanim_ad'],
            },
        ),
        migrations.CreateModel(
            name='OlcumSinavDers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolum', models.CharField(choices=[('sozel', 'Sözel'), ('sayisal', 'Sayısal'), ('genel', 'Genel')], default='genel', max_length=10, verbose_name='Bölüm')),
                ('soru_sayisi', models.PositiveSmallIntegerField(default=0, verbose_name='Soru sayısı')),
                ('katsayi', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Katsayı')),
                ('sira', models.PositiveSmallIntegerField(default=1, verbose_name='Sıra')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='olcme_sinav_dersleri', to='takip.ders', verbose_name='Ders')),
                ('sinav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olcme_dersleri', to='takip.kttsinav', verbose_name='Sınav')),
            ],
            options={
                'verbose_name': 'Sınav ders bloğu',
                'verbose_name_plural': 'Sınav ders blokları',
                'ordering': ['sinav_id', 'sira', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OlcumSinavSablon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Şablon adı')),
                ('sinav_turu', models.CharField(max_length=20, verbose_name='Sınav türü')),
                ('sinif_seviyesi', models.CharField(max_length=30, verbose_name='Sınıf seviyesi')),
                ('soru_sayisi', models.PositiveSmallIntegerField(verbose_name='Soru sayısı')),
                ('secenek_sayisi', models.PositiveSmallIntegerField(default=4)),
                ('aciklama', models.TextField(blank=True)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_olcme_sablonlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sınav şablonu',
                'verbose_name_plural': 'Sınav şablonları',
                'ordering': ['-olusturulma'],
            },
        ),
        migrations.CreateModel(
            name='OlcumSablonDers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolum', models.CharField(default='genel', max_length=10)),
                ('soru_sayisi', models.PositiveSmallIntegerField(default=0)),
                ('katsayi', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('sira', models.PositiveSmallIntegerField(default=1)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='takip.ders', verbose_name='Ders')),
                ('sablon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dersler', to='takip.olcumsinavsablon', verbose_name='Şablon')),
            ],
            options={
                'ordering': ['sablon_id', 'sira'],
            },
        ),
        migrations.CreateModel(
            name='OlcumSoru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru_no', models.PositiveSmallIntegerField(verbose_name='Soru no')),
                ('bolum', models.CharField(choices=[('sozel', 'Sözel'), ('sayisal', 'Sayısal'), ('genel', 'Genel')], default='genel', max_length=10, verbose_name='Bölüm')),
                ('beceri_turu', models.CharField(blank=True, choices=[('bilgi', 'Bilgi'), ('kavrama', 'Kavrama'), ('uygulama', 'Uygulama'), ('analiz', 'Analiz'), ('problem', 'Problem çözme')], max_length=20, verbose_name='Beceri türü')),
                ('zorluk', models.CharField(blank=True, choices=[('kolay', 'Kolay'), ('orta', 'Orta'), ('zor', 'Zor')], max_length=10, verbose_name='Zorluk')),
                ('soru_turu', models.CharField(choices=[('coktan_secmeli', 'Çoktan seçmeli'), ('dogru_yanlis', 'Doğru / Yanlış')], default='coktan_secmeli', max_length=20, verbose_name='Soru türü')),
                ('ogretmen_notu', models.CharField(blank=True, max_length=300, verbose_name='Öğretmen notu')),
                ('zimmet_tamam', models.BooleanField(default=False, editable=False, verbose_name='Zimmet tamam')),
                ('kazanim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorular', to='takip.olcumkazanim', verbose_name='Kazanım')),
                ('konu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olcme_sorulari', to='takip.konukatalogu', verbose_name='Konu')),
                ('sinav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olcme_sorulari', to='takip.kttsinav', verbose_name='Sınav')),
                ('sinav_ders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorular', to='takip.olcumsinavders', verbose_name='Ders bloğu')),
            ],
            options={
                'verbose_name': 'Sınav sorusu',
                'verbose_name_plural': 'Sınav soruları',
                'ordering': ['sinav_id', 'soru_no'],
            },
        ),
        migrations.CreateModel(
            name='OlcumIslemGecmisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem', models.CharField(max_length=40, verbose_name='İşlem')),
                ('aciklama', models.CharField(blank=True, max_length=300, verbose_name='Açıklama')),
                ('eski_deger', models.JSONField(blank=True, default=dict)),
                ('yeni_deger', models.JSONField(blank=True, default=dict)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olcme_islemleri', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('sinav', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='olcme_islem_gecmisi', to='takip.kttsinav', verbose_name='Sınav')),
                ('soru', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='islem_gecmisi', to='takip.olcumsoru', verbose_name='Soru')),
            ],
            options={
                'verbose_name': 'Ölçme işlem geçmişi',
                'verbose_name_plural': 'Ölçme işlem geçmişi',
                'ordering': ['-olusturulma', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OlcumCevapAnahtari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitapcik', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1, verbose_name='Kitapçık')),
                ('dogru_secenek', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='Doğru şık')),
                ('iptal', models.BooleanField(default=False, verbose_name='İptal edildi')),
                ('ek_dogru_secenekler', models.JSONField(blank=True, default=list, verbose_name='Ek doğru şıklar')),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cevap_anahtarlari', to='takip.olcumsoru', verbose_name='Soru')),
            ],
            options={
                'verbose_name': 'Cevap anahtarı',
                'verbose_name_plural': 'Cevap anahtarları',
            },
        ),
        migrations.CreateModel(
            name='OlcumUnite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinif_seviyesi', models.CharField(max_length=30, verbose_name='Sınıf seviyesi')),
                ('brans', models.CharField(max_length=20, verbose_name='Branş')),
                ('unite_ad', models.CharField(max_length=200, verbose_name='Ünite adı')),
                ('sira', models.PositiveSmallIntegerField(default=1, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ünite',
                'verbose_name_plural': 'Üniteler',
                'ordering': ['sinif_seviyesi', 'brans', 'sira', 'unite_ad'],
                'constraints': [models.UniqueConstraint(fields=('sinif_seviyesi', 'brans', 'unite_ad'), name='olcum_unite_benzersiz')],
            },
        ),
        migrations.AddField(
            model_name='olcumsoru',
            name='unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorular', to='takip.olcumunite', verbose_name='Ünite'),
        ),
        migrations.CreateModel(
            name='OlcumSablonSoru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru_no', models.PositiveSmallIntegerField()),
                ('bolum', models.CharField(default='genel', max_length=10)),
                ('beceri_turu', models.CharField(blank=True, max_length=20)),
                ('zorluk', models.CharField(blank=True, max_length=10)),
                ('dogru_secenek', models.CharField(blank=True, max_length=1)),
                ('ders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='takip.ders')),
                ('kazanim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='takip.olcumkazanim')),
                ('konu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='takip.konukatalogu')),
                ('sablon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorular', to='takip.olcumsinavsablon', verbose_name='Şablon')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='takip.olcumunite')),
            ],
            options={
                'ordering': ['sablon_id', 'soru_no'],
            },
        ),
        migrations.AddField(
            model_name='konukatalogu',
            name='unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='konular', to='takip.olcumunite', verbose_name='Ünite'),
        ),
        migrations.AddConstraint(
            model_name='olcumkazanim',
            constraint=models.UniqueConstraint(fields=('konu', 'kazanim_ad'), name='olcum_kazanim_benzersiz'),
        ),
        migrations.AddConstraint(
            model_name='olcumcevapanahtari',
            constraint=models.UniqueConstraint(fields=('soru', 'kitapcik'), name='olcum_anahtar_kitapcik_benzersiz'),
        ),
        migrations.AddConstraint(
            model_name='olcumsoru',
            constraint=models.UniqueConstraint(fields=('sinav', 'soru_no'), name='olcum_soru_no_benzersiz'),
        ),
        migrations.AddConstraint(
            model_name='olcumsablonsoru',
            constraint=models.UniqueConstraint(fields=('sablon', 'soru_no'), name='olcum_sablon_soru_no_benzersiz'),
        ),
    ]
