# Generated by Django 6.1 on 2026-08-13 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0082_olcme_degerlendirme_merkezi'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlcumTalebeCevap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secilen', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('BOS', 'Boş')], default='BOS', max_length=4, verbose_name='Seçilen şık')),
                ('dogru_mu', models.BooleanField(editable=False, null=True, verbose_name='Doğru mu')),
                ('kitapcik', models.CharField(default='A', max_length=1, verbose_name='Kitapçık')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('sinav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talebe_cevaplari', to='takip.kttsinav', verbose_name='Sınav')),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talebe_cevaplari', to='takip.olcumsoru', verbose_name='Soru')),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olcme_cevaplari', to='takip.talebe', verbose_name='Talebe')),
            ],
            options={
                'verbose_name': 'Talebe soru cevabı',
                'verbose_name_plural': 'Talebe soru cevapları',
                'constraints': [models.UniqueConstraint(fields=('sinav', 'talebe', 'soru'), name='olcum_talebe_soru_cevap_benzersiz')],
            },
        ),
    ]
