# Generated by Django 6.1 on 2026-08-17 17:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0083_olcum_talebe_cevap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SozelSayisalDeneme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Deneme adı')),
                ('sinav_tarihi', models.DateField(verbose_name='Sınav tarihi')),
                ('soru_formati', models.PositiveSmallIntegerField(choices=[(90, '90 soru'), (75, '75 soru')], default=90, verbose_name='Soru formatı')),
                ('sinif_seviyesi', models.CharField(help_text='Örn. 6, 7, 8', max_length=30, verbose_name='Sınıf seviyesi')),
                ('hedef_siniflar', models.CharField(blank=True, help_text='Örn. 7-A, 7-B', max_length=200, verbose_name='Hedef sınıflar')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('veliye_goster', models.BooleanField(default=True, verbose_name='Veli panelinde göster')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('etut_hocasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ss_denemeleri', to='takip.etuthocasi', verbose_name='Etüt hocası')),
                ('haric_talebeler', models.ManyToManyField(blank=True, related_name='ss_deneme_haric', to='takip.talebe', verbose_name='Katılmayan / hariç talebeler')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_ss_denemeler', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Sözel–sayısal deneme',
                'verbose_name_plural': 'Sözel–sayısal denemeler',
                'ordering': ['-sinav_tarihi', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SozelSayisalSonuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sozel_dogru', models.PositiveIntegerField(default=0)),
                ('sozel_yanlis', models.PositiveIntegerField(default=0)),
                ('sozel_bos', models.PositiveIntegerField(default=0)),
                ('sozel_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('sayisal_dogru', models.PositiveIntegerField(default=0)),
                ('sayisal_yanlis', models.PositiveIntegerField(default=0)),
                ('sayisal_bos', models.PositiveIntegerField(default=0)),
                ('sayisal_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('toplam_dogru', models.PositiveIntegerField(default=0)),
                ('toplam_yanlis', models.PositiveIntegerField(default=0)),
                ('toplam_bos', models.PositiveIntegerField(default=0)),
                ('toplam_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('puan', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('deneme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sonuclar', to='takip.sozelsayisaldeneme', verbose_name='Deneme')),
                ('kaydeden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaydettigi_ss_deneme_sonuclari', to=settings.AUTH_USER_MODEL, verbose_name='Kaydeden')),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ss_deneme_sonuclari', to='takip.talebe', verbose_name='Talebe')),
            ],
            options={
                'verbose_name': 'Sözel–sayısal sonuç',
                'verbose_name_plural': 'Sözel–sayısal sonuçlar',
                'ordering': ['-toplam_net', 'talebe__ad_soyad'],
            },
        ),
        migrations.CreateModel(
            name='SozelSayisalBransSonuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brans', models.CharField(choices=[('turkce', 'Türkçe'), ('sosyal', 'Sosyal'), ('din', 'Din'), ('ingilizce', 'İngilizce'), ('matematik', 'Matematik'), ('fen', 'Fen')], max_length=20, verbose_name='Branş')),
                ('dogru', models.PositiveIntegerField(default=0)),
                ('yanlis', models.PositiveIntegerField(default=0)),
                ('bos', models.PositiveIntegerField(default=0)),
                ('net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('sonuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brans_satirlari', to='takip.sozelsayisalsonuc', verbose_name='Sonuç')),
            ],
            options={
                'verbose_name': 'Sözel–sayısal branş sonucu',
                'verbose_name_plural': 'Sözel–sayısal branş sonuçları',
            },
        ),
        migrations.AddConstraint(
            model_name='sozelsayisalsonuc',
            constraint=models.UniqueConstraint(fields=('deneme', 'talebe'), name='ss_deneme_talebe_tek_sonuc'),
        ),
        migrations.AddConstraint(
            model_name='sozelsayisalbranssonuc',
            constraint=models.UniqueConstraint(fields=('sonuc', 'brans'), name='ss_deneme_sonuc_brans_benzersiz'),
        ),
    ]
