# Generated by Django 6.1 on 2026-08-18 07:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0084_sozel_sayisal_deneme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuzAtamasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuz_baslangic', models.PositiveSmallIntegerField(verbose_name='Cüz başlangıç')),
                ('cuz_bitis', models.PositiveSmallIntegerField(verbose_name='Cüz bitiş')),
                ('durum', models.CharField(choices=[('baslanmadi', 'Başlanmadı'), ('okunuyor', 'Okunuyor'), ('tamamlandi', 'Tamamlandı'), ('gecikmis', 'Gecikmiş'), ('muaf', 'Muaf'), ('devredildi', 'Devredildi')], default='baslanmadi', max_length=20, verbose_name='Durum')),
                ('baslama_zamani', models.DateTimeField(blank=True, null=True)),
                ('tamamlama_zamani', models.DateTimeField(blank=True, null=True)),
                ('notlar', models.TextField(blank=True, verbose_name='Notlar')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cüz ataması',
                'verbose_name_plural': 'Cüz atamaları',
                'ordering': ['donem_id', 'katilimci__sira', 'cuz_baslangic'],
            },
        ),
        migrations.CreateModel(
            name='HatimDonemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira', models.PositiveIntegerField(verbose_name='Dönem sırası')),
                ('baslangic', models.DateTimeField(verbose_name='Başlangıç')),
                ('bitis', models.DateTimeField(verbose_name='Bitiş')),
                ('durum', models.CharField(choices=[('pending', 'Onay bekliyor'), ('active', 'Aktif'), ('completed', 'Tamamlandı'), ('skipped', 'Atlandı')], default='active', max_length=20, verbose_name='Durum')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hatim dönemi',
                'verbose_name_plural': 'Hatim dönemleri',
                'ordering': ['program_id', 'sira'],
            },
        ),
        migrations.CreateModel(
            name='DonemTamamlamaKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem', models.CharField(choices=[('basladi', 'Okumaya başladı'), ('tamamladi', 'Dönemi tamamladı'), ('geri_alindi', 'Geri alındı'), ('muaf', 'Muaf'), ('devredildi', 'Devredildi'), ('gecikmis', 'Gecikmiş işaretlendi')], max_length=20, verbose_name='İşlem')),
                ('zaman', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Zaman')),
                ('not_metni', models.TextField(blank=True, verbose_name='Not')),
                ('atama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kayitlar', to='takip.cuzatamasi', verbose_name='Atama')),
                ('yapan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hatim_kayitlari', to=settings.AUTH_USER_MODEL, verbose_name='Yapan')),
            ],
            options={
                'verbose_name': 'Dönem tamamlama kaydı',
                'verbose_name_plural': 'Dönem tamamlama kayıtları',
                'ordering': ['-zaman', '-id'],
            },
        ),
        migrations.AddField(
            model_name='cuzatamasi',
            name='donem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuz_atamalari', to='takip.hatimdonemi', verbose_name='Dönem'),
        ),
        migrations.CreateModel(
            name='HatimKatilimcisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('varsayilan_cuz_bas', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Varsayılan cüz başlangıç')),
                ('varsayilan_cuz_bit', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Varsayılan cüz bitiş')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('personel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hatim_katilimlari', to='takip.personelprofili', verbose_name='Personel')),
                ('talebe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hatim_katilimlari', to='takip.talebe', verbose_name='Talebe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hatim_katilimlari', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Hatim katılımcısı',
                'verbose_name_plural': 'Hatim katılımcıları',
                'ordering': ['sira', 'id'],
            },
        ),
        migrations.AddField(
            model_name='cuzatamasi',
            name='devredilen_katilimci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devralinan_cuzler', to='takip.hatimkatilimcisi', verbose_name='Devredilen katılımcı'),
        ),
        migrations.AddField(
            model_name='cuzatamasi',
            name='katilimci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuz_atamalari', to='takip.hatimkatilimcisi', verbose_name='Katılımcı'),
        ),
        migrations.CreateModel(
            name='HatimProgrami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200, verbose_name='Hatim adı')),
                ('tur', models.CharField(choices=[('personel', 'Personel Hatmi'), ('talebe', 'Talebe Hatmi'), ('sinif', 'Sınıf Hatmi'), ('veli', 'Veli Hatmi')], default='personel', max_length=20, verbose_name='Hatim türü')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('baslangic_tarihi', models.DateField(verbose_name='Başlangıç tarihi')),
                ('program_bitis_tarihi', models.DateField(blank=True, help_text='Boş bırakılırsa yetkili durdurana kadar devam eder.', null=True, verbose_name='Program bitiş tarihi')),
                ('son_tamamlama_saati', models.TimeField(default='20:00', verbose_name='Son tamamlama saati')),
                ('kisi_basina_cuz', models.PositiveSmallIntegerField(default=1, verbose_name='Kişi başına cüz sayısı')),
                ('cuz_dagitim_yontemi', models.CharField(choices=[('auto', 'Otomatik sırayla'), ('manual', 'Manuel dağıtım')], default='auto', max_length=10, verbose_name='Cüz dağıtım yöntemi')),
                ('tekrar_turu', models.CharField(choices=[('once', 'Sadece bir kez'), ('daily', 'Her gün'), ('every_2', '2 günde bir'), ('every_3', '3 günde bir'), ('weekly', 'Haftalık'), ('custom', 'Özel gün aralığı')], default='every_2', max_length=20, verbose_name='Tekrarlama')),
                ('tekrar_gun_araligi', models.PositiveSmallIntegerField(default=2, help_text='“Her N günde bir” için N değeri.', verbose_name='Özel gün aralığı')),
                ('cuz_donem_stratejisi', models.CharField(choices=[('same', 'Aynı cüzler tekrar okunacak'), ('rotate', 'Cüzler her dönemde sırayla döndürülecek'), ('redistribute', 'Cüzler her dönemde yeniden dağıtılacak')], default='same', max_length=20, verbose_name='Dönemler arası cüz stratejisi')),
                ('hafta_sonu_dahil', models.BooleanField(default=True, verbose_name='Hafta sonlarını dahil et')),
                ('yeni_donem_otomatik', models.BooleanField(default=True, verbose_name='Yeni dönem otomatik başlasın')),
                ('eksik_aktar', models.BooleanField(default=False, verbose_name='Eksik okumayı sonraki döneme aktar')),
                ('gecikmis_sakla', models.BooleanField(default=True, verbose_name='Yeni dönemde önceki eksikleri gecikmiş olarak sakla')),
                ('yarim_son_donem', models.BooleanField(default=True, verbose_name='Bitiş tarihinde yarım kalan son dönemi oluştur')),
                ('durum', models.CharField(choices=[('draft', 'Taslak'), ('active', 'Aktif'), ('paused', 'Duraklatıldı'), ('completed', 'Tamamlandı'), ('stopped', 'Durduruldu')], default='draft', max_length=20, verbose_name='Durum')),
                ('dua_yapildi', models.BooleanField(default=False, verbose_name='Dua yapıldı')),
                ('tamamlanma_zamani', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma zamanı')),
                ('hatirlatma_program_baslangic', models.BooleanField(default=True)),
                ('hatirlatma_yeni_donem', models.BooleanField(default=True)),
                ('hatirlatma_bitis_12h', models.BooleanField(default=True)),
                ('hatirlatma_bitis_2h', models.BooleanField(default=True)),
                ('hatirlatma_sure_gecti', models.BooleanField(default=True)),
                ('hatirlatma_program_tamamlandi', models.BooleanField(default=True)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_hatimler', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Hatim programı',
                'verbose_name_plural': 'Hatim programları',
                'ordering': ['-baslangic_tarihi', '-id'],
            },
        ),
        migrations.AddField(
            model_name='hatimkatilimcisi',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='katilimcilar', to='takip.hatimprogrami', verbose_name='Program'),
        ),
        migrations.CreateModel(
            name='HatimHatirlatmasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tetik', models.CharField(choices=[('program_baslangic', 'Program başladığında'), ('yeni_donem', 'Yeni dönem başladığında'), ('bitis_12h', 'Dönem bitimine 12 saat kala'), ('bitis_2h', 'Dönem bitimine 2 saat kala'), ('sure_gecti', 'Süre geçtiğinde'), ('program_tamamlandi', 'Hatim tamamlandığında')], max_length=30, verbose_name='Tetik')),
                ('gonderim_zamani', models.DateTimeField(auto_now_add=True)),
                ('alici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hatim_hatirlatmalari', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı')),
                ('bildirim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hatim_hatirlatmalari', to='takip.bildirim')),
                ('donem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hatirlatmalar', to='takip.hatimdonemi', verbose_name='Dönem')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hatirlatmalar', to='takip.hatimprogrami', verbose_name='Program')),
            ],
            options={
                'verbose_name': 'Hatim hatırlatması',
                'verbose_name_plural': 'Hatim hatırlatmaları',
                'ordering': ['-gonderim_zamani', '-id'],
            },
        ),
        migrations.AddField(
            model_name='hatimdonemi',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donemler', to='takip.hatimprogrami', verbose_name='Program'),
        ),
        migrations.AddConstraint(
            model_name='hatimdonemi',
            constraint=models.UniqueConstraint(fields=('program', 'sira'), name='benzersiz_hatim_donem_sira'),
        ),
    ]
