# Generated by Django 6.1 on 2026-08-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0085_hatim_takip'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeliAnketCevap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seminer_adi', models.CharField(default='Veli Eğitim Semineri', max_length=200, verbose_name='Seminer adı')),
                ('genel_degerlendirme', models.PositiveSmallIntegerField(verbose_name='Genel değerlendirme (1-5)')),
                ('konu_secimi_gorus', models.TextField(blank=True, verbose_name='Konu seçimi hakkındaki görüş')),
                ('konusmaci_gorus', models.TextField(blank=True, verbose_name='Konuşmacı hakkındaki görüş')),
                ('istifade_duzeyi', models.CharField(blank=True, choices=[('Hiç', 'Hiç'), ('Az', 'Az'), ('Orta', 'Orta'), ('Çok', 'Çok'), ('Çok Fazla', 'Çok Fazla')], max_length=20, verbose_name='İstifade düzeyi')),
                ('oneriler', models.TextField(blank=True, verbose_name='Görüş ve öneriler')),
                ('olusturulma', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim zamanı')),
            ],
            options={
                'verbose_name': 'Veli anket cevabı',
                'verbose_name_plural': 'Veli anket cevapları',
                'ordering': ['-olusturulma'],
            },
        ),
    ]
