# Generated by Django 6.1 on 2026-08-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0086_velianketcevap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='velianketcevap',
            name='istifade_duzeyi',
        ),
        migrations.RemoveField(
            model_name='velianketcevap',
            name='konu_secimi_gorus',
        ),
        migrations.AddField(
            model_name='velianketcevap',
            name='istifade_puani',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='İstifade puanı (1-5)'),
        ),
        migrations.AddField(
            model_name='velianketcevap',
            name='konu_ihtiyaci_cevap',
            field=models.CharField(blank=True, choices=[('Evet', 'Evet'), ('Kısmen', 'Kısmen'), ('Hayır', 'Hayır')], max_length=10, verbose_name='Konu ihtiyaca cevap verdi mi'),
        ),
        migrations.AddField(
            model_name='velianketcevap',
            name='onerilen_konular',
            field=models.TextField(blank=True, verbose_name='Önerilen konular'),
        ),
        migrations.AddField(
            model_name='velianketcevap',
            name='sinif',
            field=models.CharField(blank=True, choices=[('5. sınıf', '5. sınıf'), ('6. sınıf', '6. sınıf'), ('7. sınıf', '7. sınıf'), ('8. sınıf', '8. sınıf')], max_length=20, verbose_name='Talebenin sınıfı'),
        ),
        migrations.AlterField(
            model_name='velianketcevap',
            name='genel_degerlendirme',
            field=models.TextField(blank=True, verbose_name='Genel değerlendirme'),
        ),
        migrations.AlterField(
            model_name='velianketcevap',
            name='oneriler',
            field=models.TextField(blank=True, verbose_name='Diğer değerlendirme/öneriler'),
        ),
    ]
