# Generated by Django 6.1 on 2026-08-24 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0087_remove_velianketcevap_istifade_duzeyi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OgretmenOdemeAktifDonem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic', models.DateField(verbose_name='Başlangıç')),
                ('bitis', models.DateField(verbose_name='Bitiş')),
                ('guncellendi', models.DateTimeField(auto_now=True, verbose_name='Güncellendi')),
                ('guncelleyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Aktif ödeme dönemi penceresi',
                'verbose_name_plural': 'Aktif ödeme dönemi penceresi',
            },
        ),
    ]
