# Generated by Django 6.1 on 2026-09-14 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0088_ogretmenodemeaktifdonem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuzatamasi',
            name='devredilen_katilimci',
        ),
        migrations.RemoveField(
            model_name='cuzatamasi',
            name='donem',
        ),
        migrations.RemoveField(
            model_name='cuzatamasi',
            name='katilimci',
        ),
        migrations.RemoveField(
            model_name='donemtamamlamakaydi',
            name='atama',
        ),
        migrations.RemoveField(
            model_name='donemtamamlamakaydi',
            name='yapan',
        ),
        migrations.RemoveConstraint(
            model_name='hatimdonemi',
            name='benzersiz_hatim_donem_sira',
        ),
        migrations.RemoveField(
            model_name='hatimhatirlatmasi',
            name='donem',
        ),
        migrations.RemoveField(
            model_name='hatimhatirlatmasi',
            name='alici',
        ),
        migrations.RemoveField(
            model_name='hatimhatirlatmasi',
            name='bildirim',
        ),
        migrations.RemoveField(
            model_name='hatimhatirlatmasi',
            name='program',
        ),
        migrations.RemoveField(
            model_name='hatimkatilimcisi',
            name='personel',
        ),
        migrations.RemoveField(
            model_name='hatimkatilimcisi',
            name='program',
        ),
        migrations.RemoveField(
            model_name='hatimkatilimcisi',
            name='talebe',
        ),
        migrations.RemoveField(
            model_name='hatimkatilimcisi',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hatimprogrami',
            name='olusturan',
        ),
        migrations.DeleteModel(
            name='CuzAtamasi',
        ),
        migrations.DeleteModel(
            name='DonemTamamlamaKaydi',
        ),
        migrations.RemoveField(
            model_name='hatimdonemi',
            name='program',
        ),
        migrations.DeleteModel(
            name='HatimHatirlatmasi',
        ),
        migrations.DeleteModel(
            name='HatimKatilimcisi',
        ),
        migrations.DeleteModel(
            name='HatimDonemi',
        ),
        migrations.DeleteModel(
            name='HatimProgrami',
        ),
    ]
