# Generated by Django 6.1 on 2026-09-14 22:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0089_remove_cuzatamasi_devredilen_katilimci_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SabahBeslenmeGunlukMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(unique=True, verbose_name='Tarih')),
                ('urun', models.CharField(max_length=80, verbose_name='Beslenme ürünü')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim fiyat')),
                ('siparis_son_saati', models.TimeField(verbose_name='Sipariş son saati')),
                ('durum', models.CharField(choices=[('acik', 'Açık'), ('kapali', 'Kapalı')], default='acik', max_length=12, verbose_name='Sipariş durumu')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('guncelleyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guncelledigi_sabah_beslenme_menuleri', to=settings.AUTH_USER_MODEL)),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_sabah_beslenme_menuleri', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sabah beslenmesi günlük menü',
                'verbose_name_plural': 'Sabah beslenmesi günlük menüler',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='SabahBeslenmeSiparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.PositiveIntegerField(default=0, verbose_name='Adet')),
                ('odeme_turu', models.CharField(choices=[('pesin', 'Peşin'), ('borc', 'Borç')], default='pesin', max_length=8, verbose_name='Ödeme durumu')),
                ('teslim_edildi', models.BooleanField(default=False, verbose_name='Satış / teslim')),
                ('teslim_saati', models.DateTimeField(blank=True, null=True, verbose_name='Satış saati')),
                ('borc_kaydi_olustu', models.BooleanField(default=False, verbose_name='Borç kaydı oluştu')),
                ('borc_tutari', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Borç tutarı')),
                ('borc_kapatildi', models.BooleanField(default=False, verbose_name='Borç kapatıldı')),
                ('borc_kapatma_saati', models.DateTimeField(blank=True, null=True, verbose_name='Borç kapatma saati')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('borc_kapatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kapattigi_sabah_beslenme_borclari', to=settings.AUTH_USER_MODEL, verbose_name='Borcu kapatan')),
                ('etut_hocasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sabah_beslenme_siparisleri', to='takip.etuthocasi', verbose_name='Etüt hocası')),
                ('kaydeden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaydettigi_sabah_beslenme_siparisleri', to=settings.AUTH_USER_MODEL, verbose_name='Siparişi kaydeden')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siparisler', to='takip.sabahbeslenmegunlukmenu', verbose_name='Günlük menü')),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sabah_beslenme_siparisleri', to='takip.talebe', verbose_name='Talebe')),
                ('teslim_eden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teslim_ettigi_sabah_beslenme_siparisleri', to=settings.AUTH_USER_MODEL, verbose_name='Satışı yapan')),
            ],
            options={
                'verbose_name': 'Sabah beslenmesi siparişi',
                'verbose_name_plural': 'Sabah beslenmesi siparişleri',
                'ordering': ['talebe__ad_soyad', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SabahBeslenmeIslemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem', models.CharField(choices=[('siparis', 'Sipariş'), ('odeme', 'Ödeme tercihi'), ('teslim', 'Teslim / satış'), ('teslim_geri', 'Teslim geri alındı'), ('borc_kapat', 'Borç kapatıldı')], max_length=16)),
                ('detay', models.CharField(blank=True, max_length=240)),
                ('zaman', models.DateTimeField(auto_now_add=True)),
                ('yapan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sabah_beslenme_islem_loglari', to=settings.AUTH_USER_MODEL)),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='islem_loglari', to='takip.sabahbeslenmesiparis')),
            ],
            options={
                'verbose_name': 'Sabah beslenmesi işlem kaydı',
                'verbose_name_plural': 'Sabah beslenmesi işlem kayıtları',
                'ordering': ['-zaman', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='sabahbeslenmesiparis',
            index=models.Index(fields=['teslim_edildi', 'borc_kaydi_olustu', 'borc_kapatildi'], name='sb_siparis_borc_idx'),
        ),
        migrations.AddConstraint(
            model_name='sabahbeslenmesiparis',
            constraint=models.UniqueConstraint(fields=('menu', 'talebe'), name='sb_siparis_menu_talebe_tek'),
        ),
        migrations.AddConstraint(
            model_name='sabahbeslenmesiparis',
            constraint=models.CheckConstraint(condition=models.Q(('borc_kaydi_olustu', False), ('teslim_edildi', True), _connector='OR'), name='sb_borc_sadece_teslim'),
        ),
        migrations.AddConstraint(
            model_name='sabahbeslenmesiparis',
            constraint=models.CheckConstraint(condition=models.Q(('teslim_edildi', False), ('adet__gt', 0), _connector='OR'), name='sb_teslim_adet_pozitif'),
        ),
    ]
