# Generated by Django 6.1 on 2026-09-15 18:59

from django.db import migrations, models


def stamp_analitik_okuma_kodu(apps, schema_editor):
    Ders = apps.get_model("takip", "Ders")
    for ders in Ders.objects.all():
        ad = (ders.ad or "").strip().casefold().replace("ı", "i")
        if ad == "analitik okuma":
            ders.kod = "analitik_okuma"
            ders.save(update_fields=["kod"])


def unstamp_analitik_okuma_kodu(apps, schema_editor):
    Ders = apps.get_model("takip", "Ders")
    Ders.objects.filter(kod="analitik_okuma").update(kod=None)


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0090_sabah_beslenmesi'),
    ]

    operations = [
        migrations.AddField(
            model_name='ders',
            name='kod',
            field=models.CharField(blank=True, help_text='Sistem içi sabit kimlik. Analitik Okuma için: analitik_okuma', max_length=64, null=True, unique=True, verbose_name='Ders kodu'),
        ),
        migrations.RunPython(stamp_analitik_okuma_kodu, unstamp_analitik_okuma_kodu),
        migrations.AddField(
            model_name='ogretmenhaftalikkonu',
            name='analitik_alan',
            field=models.CharField(blank=True, choices=[('gorsel_grafik', 'Görsel ve Grafik Çözümleme'), ('sozel_mantik', 'Sözel Mantık ve Muhakeme'), ('cikarma_anlama', 'Çıkarım Yapma ve Derin Anlama'), ('akici_okuma', 'Akıcı ve Sesli Okuma'), ('stratejik_soru', 'Stratejik Soru Çözme Yaklaşımı')], max_length=32, verbose_name='Analitik Okuma alanı'),
        ),
        migrations.AddField(
            model_name='ogretmenhaftalikkonu',
            name='durum',
            field=models.CharField(choices=[('taslak', 'Taslak'), ('tamamlandi', 'Tamamlandı')], default='tamamlandi', max_length=16, verbose_name='Kayıt durumu'),
        ),
        migrations.AddField(
            model_name='ogretmenhaftalikkonu',
            name='haftanin_kavrami',
            field=models.CharField(blank=True, max_length=120, verbose_name='Haftanın kavramı'),
        ),
        migrations.AddField(
            model_name='ogretmensinavnotu',
            name='kavram_puani',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Yalnızca Analitik Okuma. 1–10 yıldız.', null=True, verbose_name='Kavram Öğretimi'),
        ),
        migrations.AddConstraint(
            model_name='ogretmenhaftalikkonu',
            constraint=models.CheckConstraint(condition=models.Q(('analitik_alan', ''), ('analitik_alan__in', ['gorsel_grafik', 'sozel_mantik', 'cikarma_anlama', 'akici_okuma', 'stratejik_soru']), _connector='OR'), name='ogretmen_haftalik_konu_analitik_alan'),
        ),
        migrations.AddConstraint(
            model_name='ogretmensinavnotu',
            constraint=models.CheckConstraint(condition=models.Q(('kavram_puani__isnull', True), models.Q(('kavram_puani__gte', 1), ('kavram_puani__lte', 10)), _connector='OR'), name='ogretmen_sinav_notu_kavram_1_10'),
        ),
    ]
