# Generated by Django 6.1 on 2026-09-16 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0091_analitik_okuma_degerlendirme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushAbonelik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True, verbose_name='Endpoint')),
                ('p256dh', models.CharField(max_length=255, verbose_name='p256dh anahtarı')),
                ('auth', models.CharField(max_length=255, verbose_name='Auth anahtarı')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='Cihaz/Tarayıcı')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_abonelikleri', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Push aboneliği',
                'verbose_name_plural': 'Push abonelikleri',
                'ordering': ['-olusturulma'],
                'indexes': [models.Index(fields=['user'], name='takip_pusha_user_id_4ccd8c_idx')],
            },
        ),
    ]
