# Generated by Django 6.1 on 2026-09-17 22:25

import takip.ekran_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0093_ekranogegrubu_ekranislemkaydi_ekrankonumu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekranmedya',
            name='dosya',
            field=models.FileField(storage=takip.ekran_storage.ekran_depolama, upload_to='ekran/medya/%Y/%m/', verbose_name='Dosya'),
        ),
        migrations.AlterField(
            model_name='ekranmedya',
            name='onizleme',
            field=models.ImageField(blank=True, null=True, storage=takip.ekran_storage.ekran_depolama, upload_to='ekran/onizleme/%Y/%m/', verbose_name='Küçük ön izleme'),
        ),
        migrations.AlterField(
            model_name='ekranmedyasayfasi',
            name='gorsel',
            field=models.ImageField(storage=takip.ekran_storage.ekran_depolama, upload_to='ekran/pdf/%Y/%m/', verbose_name='Sayfa görseli'),
        ),
        migrations.AlterField(
            model_name='ekransablon',
            name='onizleme',
            field=models.ImageField(blank=True, null=True, storage=takip.ekran_storage.ekran_depolama, upload_to='ekran/sablon/', verbose_name='Ön izleme'),
        ),
        migrations.AlterField(
            model_name='ekransahne',
            name='onizleme',
            field=models.ImageField(blank=True, null=True, storage=takip.ekran_storage.ekran_depolama, upload_to='ekran/sahne/%Y/%m/', verbose_name='Ön izleme görseli'),
        ),
    ]
