# Generated by Django 5.2.17 on 2026-09-21 17:30

import django.db.models.deletion
import takip.akilli_tahta_storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takip", "0096_soru_takip_din_kulturu_ders_seed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AkilliTahtaDosya",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "baslik",
                    models.CharField(max_length=200, verbose_name="Dosya başlığı"),
                ),
                (
                    "dosya",
                    models.FileField(
                        storage=takip.akilli_tahta_storage.akilli_tahta_depolama,
                        upload_to="",
                        verbose_name="Dosya",
                    ),
                ),
                (
                    "dosya_turu",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("jpg", "JPG"),
                            ("jpeg", "JPEG"),
                            ("png", "PNG"),
                            ("webp", "WEBP"),
                            ("mp4", "MP4"),
                        ],
                        help_text="Yüklemede içeriğin ilk baytlarından (magic number) tespit edilir.",
                        max_length=10,
                        verbose_name="Dosya türü",
                    ),
                ),
                (
                    "icerik_turu",
                    models.CharField(
                        choices=[
                            ("deneme", "Deneme"),
                            ("test", "Test"),
                            ("calisma_kagidi", "Çalışma Kâğıdı"),
                            ("gorsel", "Görsel"),
                            ("video", "Video"),
                        ],
                        max_length=20,
                        verbose_name="İçerik türü",
                    ),
                ),
                ("aciklama", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "tum_siniflar",
                    models.BooleanField(
                        default=False, verbose_name="Tüm sınıflara gönder"
                    ),
                ),
                (
                    "ust_sirada",
                    models.BooleanField(
                        default=False, verbose_name="Üst sırada göster"
                    ),
                ),
                (
                    "indirme_izni",
                    models.BooleanField(
                        default=True, verbose_name="İndirmeye izin ver"
                    ),
                ),
                (
                    "yayin_baslangic",
                    models.DateTimeField(verbose_name="Yayın başlangıç tarihi/saati"),
                ),
                (
                    "yayin_bitis",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Yayından kaldırılma tarihi/saati",
                    ),
                ),
                (
                    "durum",
                    models.CharField(
                        choices=[
                            ("taslak", "Taslak"),
                            ("yayinda", "Yayında"),
                            ("arsivlendi", "Arşivlendi"),
                        ],
                        default="taslak",
                        max_length=10,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "dosya_hash",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="SHA-256"
                    ),
                ),
                (
                    "dosya_boyutu",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Dosya boyutu (bayt)"
                    ),
                ),
                (
                    "mime",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="MIME türü"
                    ),
                ),
                ("olusturulma", models.DateTimeField(auto_now_add=True)),
                ("guncellenme", models.DateTimeField(auto_now=True)),
                (
                    "ders",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="akilli_tahta_dosyalari",
                        to="takip.ders",
                        verbose_name="Ders",
                    ),
                ),
                (
                    "yukleyen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="yukledigi_akilli_tahta_dosyalari",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yükleyen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Akıllı tahta dosyası",
                "verbose_name_plural": "Akıllı tahta dosyaları",
                "ordering": ["-ust_sirada", "-olusturulma"],
            },
        ),
        migrations.CreateModel(
            name="AkilliTahtaHesap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sinif_seviyesi",
                    models.CharField(
                        choices=[
                            ("5", "5. Sınıflar"),
                            ("6", "6. Sınıflar"),
                            ("7", "7. Sınıflar"),
                            ("8", "8. Sınıflar"),
                        ],
                        max_length=1,
                        verbose_name="Sınıf seviyesi",
                    ),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
                ("olusturulma", models.DateTimeField(auto_now_add=True)),
                ("guncellenme", models.DateTimeField(auto_now=True)),
                (
                    "olusturan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="olusturdugu_tahta_hesaplari",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="akilli_tahta_hesabi",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı hesabı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Akıllı tahta hesabı",
                "verbose_name_plural": "Akıllı tahta hesapları",
                "ordering": ["sinif_seviyesi"],
            },
        ),
        migrations.CreateModel(
            name="AkilliTahtaIslemKaydi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aksiyon", models.CharField(max_length=50, verbose_name="Aksiyon")),
                ("detay", models.TextField(blank=True, verbose_name="Detay")),
                ("olusturulma", models.DateTimeField(auto_now_add=True)),
                (
                    "dosya",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="islem_kayitlari",
                        to="takip.akillitahtadosya",
                        verbose_name="Dosya",
                    ),
                ),
                (
                    "hesap",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="islem_kayitlari",
                        to="takip.akillitahtahesap",
                        verbose_name="Tahta hesabı",
                    ),
                ),
                (
                    "kullanici",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="akilli_tahta_islemleri",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Akıllı tahta işlem kaydı",
                "verbose_name_plural": "Akıllı tahta işlem kayıtları",
                "ordering": ["-olusturulma"],
            },
        ),
        migrations.CreateModel(
            name="AkilliTahtaHedef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sinif_seviyesi",
                    models.CharField(
                        choices=[
                            ("5", "5. Sınıflar"),
                            ("6", "6. Sınıflar"),
                            ("7", "7. Sınıflar"),
                            ("8", "8. Sınıflar"),
                        ],
                        max_length=1,
                        verbose_name="Sınıf seviyesi",
                    ),
                ),
                (
                    "dosya",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hedefler",
                        to="takip.akillitahtadosya",
                        verbose_name="Dosya",
                    ),
                ),
            ],
            options={
                "verbose_name": "Akıllı tahta hedefi",
                "verbose_name_plural": "Akıllı tahta hedefleri",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dosya", "sinif_seviyesi"),
                        name="benzersiz_akilli_tahta_hedef",
                    )
                ],
            },
        ),
    ]
