# Generated by Django 6.0.7 on 2026-09-25 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0100_aidat_finans_verilerini_sil'),
    ]

    operations = [
        migrations.CreateModel(
            name='DenemeKazanimSonucu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders_ad', models.CharField(max_length=120, verbose_name='Ders')),
                ('konu_ad', models.CharField(max_length=300, verbose_name='Kazanım / konu')),
                ('ders_key', models.CharField(db_index=True, max_length=120)),
                ('konu_key', models.CharField(db_index=True, max_length=300)),
                ('yuzde', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Başarı %')),
                ('net_dogru', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Net doğru')),
                ('net_toplam', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Net toplam')),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('deneme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kazanim_sonuclari', to='takip.denemesinavi', verbose_name='Deneme')),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deneme_kazanim_sonuclari', to='takip.talebe', verbose_name='Talebe')),
            ],
            options={
                'verbose_name': 'Deneme kazanım sonucu',
                'verbose_name_plural': 'Deneme kazanım sonuçları',
                'ordering': ['ders_ad', 'konu_ad', 'id'],
                'indexes': [models.Index(fields=['deneme', 'talebe'], name='takip_denem_deneme__7e9bb5_idx'), models.Index(fields=['deneme', 'konu_key'], name='takip_denem_deneme__64b02f_idx')],
                'constraints': [models.UniqueConstraint(fields=('deneme', 'talebe', 'ders_key', 'konu_key'), name='deneme_kazanim_benzersiz')],
            },
        ),
    ]
