# Generated by Django 6.1.1 on 2026-10-05 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0105_deneme_soru_sonucu'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinifSeviyeMesulu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinif', models.CharField(help_text='Örn. 7. Bu seviyedeki bütün şubelerin listesinde bu hoca görünür.', max_length=30, unique=True, verbose_name='Sınıf')),
                ('hoca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seviye_mesuliyetleri', to='takip.etuthocasi', verbose_name='Sınıf mesulü')),
            ],
            options={
                'verbose_name': 'Sınıf mesulü',
                'verbose_name_plural': 'Sınıf mesulleri',
                'ordering': ['sinif'],
            },
        ),
    ]
