# Generated by Django 5.2.17 on 2026-10-06 10:35

import django.db.models.deletion
import takip.ekitap_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takip", "0107_ekitap"),
    ]

    operations = [
        migrations.AddField(
            model_name="ekitapbolum",
            name="pdf_ozeti",
            field=models.CharField(
                blank=True,
                help_text="Son soru tespitinde PDF'in SHA-256 özeti.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="ekitapbolum",
            name="tespit_durumu",
            field=models.CharField(
                choices=[
                    ("yok", "Yapılmadı"),
                    ("araniyor", "Aranıyor"),
                    ("tamam", "Tamam"),
                    ("taranmis", "Taranmış PDF"),
                    ("bos", "Soru bulunamadı"),
                    ("hata", "Hata"),
                ],
                default="yok",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="ekitapbolum",
            name="tespit_notu",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="ekitapsayfa",
            name="kontrol_gerekli",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ekitapsayfa",
            name="kontrol_notu",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="ekitapsayfa",
            name="metinli",
            field=models.BooleanField(
                default=True, help_text="Sayfada yazı katmanı var mı (taranmış değil)."
            ),
        ),
        migrations.CreateModel(
            name="EKitapSoru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_no",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Bölüm içindeki test; numaralar her testte 1'den başlar.",
                    ),
                ),
                ("no", models.PositiveSmallIntegerField(verbose_name="Soru numarası")),
                (
                    "sira",
                    models.PositiveIntegerField(default=0, verbose_name="Okuma sırası"),
                ),
                ("guven", models.FloatField(default=1.0, verbose_name="Tespit güveni")),
                (
                    "kaynak",
                    models.CharField(
                        choices=[("otomatik", "Otomatik"), ("elle", "Elle")],
                        default="otomatik",
                        max_length=10,
                    ),
                ),
                (
                    "onayli",
                    models.BooleanField(
                        default=False,
                        help_text="Yönetici onayladı; otomatik tespit yeniden çalışınca korunur.",
                    ),
                ),
                (
                    "inceleme_gerekli",
                    models.BooleanField(
                        default=False,
                        help_text="Onaydan sonra PDF değişti; alanları yeniden inceleyin.",
                    ),
                ),
                ("pdf_ozeti", models.CharField(blank=True, max_length=64)),
                ("olusturulma", models.DateTimeField(auto_now_add=True)),
                ("guncellenme", models.DateTimeField(auto_now=True)),
                (
                    "bolum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sorular",
                        to="takip.ekitapbolum",
                    ),
                ),
            ],
            options={
                "verbose_name": "E-kitap sorusu",
                "verbose_name_plural": "E-kitap soruları",
                "ordering": ["bolum", "sira", "id"],
            },
        ),
        migrations.CreateModel(
            name="EKitapSoruAlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sira", models.PositiveSmallIntegerField(default=0)),
                (
                    "sayfa_sira",
                    models.PositiveIntegerField(verbose_name="Sayfa (0'dan)"),
                ),
                ("x0", models.FloatField()),
                ("y0", models.FloatField()),
                ("x1", models.FloatField()),
                ("y1", models.FloatField()),
                (
                    "gorsel",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        storage=takip.ekitap_storage.ekitap_depolama,
                        upload_to="soru/",
                    ),
                ),
                ("gorsel_imza", models.CharField(blank=True, max_length=40)),
                ("genislik", models.PositiveIntegerField(default=0)),
                ("yukseklik", models.PositiveIntegerField(default=0)),
                (
                    "soru",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alanlar",
                        to="takip.ekitapsoru",
                    ),
                ),
            ],
            options={
                "ordering": ["soru", "sira", "id"],
            },
        ),
    ]
