# Generated by Django 5.2.17 on 2026-10-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takip", "0108_ekitap_soru"),
    ]

    operations = [
        migrations.AddField(
            model_name="ekitapsoru",
            name="siklar_alan",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ekitapsoru",
            name="siklar_y",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
