# Generated by Django 5.2.17 on 2026-10-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takip", "0109_ekitap_soru_siklar"),
    ]

    operations = [
        migrations.AddField(
            model_name="ekitapbolum",
            name="sira_elle",
            field=models.BooleanField(
                default=False,
                help_text="Okuma sırası yönetimde elle düzenlendi; yeniden tespit sırayı bozmaz.",
            ),
        ),
        migrations.AddField(
            model_name="ekitapsayfa",
            name="onaylandi",
            field=models.BooleanField(
                default=False,
                help_text="Yönetici sayfayı onayladı; yeniden tespit 'Kontrol edin' işaretini geri getirmez.",
            ),
        ),
        migrations.AddField(
            model_name="ekitapsoru",
            name="gizli",
            field=models.BooleanField(
                default=False,
                help_text="Yönetimde silindi: tahtada görünmez, yeniden tespitte geri gelmez.",
            ),
        ),
    ]
