# Generated by Django 5.2.17 on 2026-10-06 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takip", "0110_ekitap_duzeltme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ekitapbolum",
            name="tespit_durumu",
            field=models.CharField(
                choices=[
                    ("yok", "Yapılmadı"),
                    ("araniyor", "Aranıyor"),
                    ("tamam", "Tamam"),
                    ("taranmis", "Taranmış PDF"),
                    ("ocr", "OCR ile bulundu"),
                    ("bos", "Soru bulunamadı"),
                    ("hata", "Hata"),
                ],
                default="yok",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="EKitapDersAkisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad", models.CharField(max_length=80, verbose_name="Ders akışı adı")),
                ("olusturulma", models.DateTimeField(auto_now_add=True)),
                ("guncellenme", models.DateTimeField(auto_now=True)),
                (
                    "kitap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ders_akislari",
                        to="takip.ekitap",
                    ),
                ),
            ],
            options={
                "verbose_name": "E-kitap ders akışı",
                "verbose_name_plural": "E-kitap ders akışları",
                "ordering": ["-guncellenme", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EKitapDersAkisiSoru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sira", models.PositiveIntegerField(default=0)),
                (
                    "akis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ogeler",
                        to="takip.ekitapdersakisi",
                    ),
                ),
                (
                    "soru",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="takip.ekitapsoru",
                    ),
                ),
            ],
            options={
                "ordering": ["sira", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("akis", "soru"), name="benzersiz_ekitap_akis_soru"
                    )
                ],
            },
        ),
    ]
