# Generated by Django 5.2.17 on 2026-10-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takip", "0111_ekitap_ocr_ders_akisi"),
    ]

    operations = [
        migrations.AddField(
            model_name="ekitapsoru",
            name="rozet_cap",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ekitapsoru",
            name="rozet_x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ekitapsoru",
            name="rozet_y",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
