# Generated by Django 5.2.17 on 2026-10-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("takip", "0112_ekitap_rozet"),
    ]

    operations = [
        migrations.AddField(
            model_name="ekitapbolum",
            name="tespit_surumu",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Soru tespiti hangi algoritma sürümüyle yapıldı; eskiyse açılışta yenilenir.",
            ),
        ),
        migrations.AddField(
            model_name="ekitapsoru",
            name="rozet_sayfa",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
