# Generated by Django 6.1.2 on 2026-10-08 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takip', '0113_ekitap_rozet_sayfa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NehariGunlukOdev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(unique=True, verbose_name='Tarih')),
                ('metin', models.CharField(max_length=300, verbose_name='Günün ödevi')),
                ('guncellenme', models.DateTimeField(auto_now=True)),
                ('guncelleyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nehari_odev_metinleri', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Nehari günlük ödev',
                'verbose_name_plural': 'Nehari günlük ödevler',
                'ordering': ['-tarih'],
            },
        ),
        migrations.CreateModel(
            name='NehariOdevIsaret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('yapildi', models.BooleanField(default=False, verbose_name='Yapıldı')),
                ('isaretlenme', models.DateTimeField(auto_now=True, verbose_name='İşaretlenme')),
                ('isaretleyen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nehari_odev_isaretleri', to=settings.AUTH_USER_MODEL, verbose_name='İşaretleyen')),
                ('talebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nehari_odev_isaretleri', to='takip.talebe', verbose_name='Talebe')),
            ],
            options={
                'verbose_name': 'Nehari ödev işareti',
                'verbose_name_plural': 'Nehari ödev işaretleri',
                'ordering': ['-tarih', 'talebe__ad_soyad'],
                'constraints': [models.UniqueConstraint(fields=('talebe', 'tarih'), name='benzersiz_nehari_odev_talebe_tarih')],
            },
        ),
    ]
